// Module included in the following assemblies:
//
// * post_installation_configuration/machine-configuration-tasks.adoc

:_mod-docs-content-type: PROCEDURE
[id="checking-mco-node-status_{context}"]
= Checking machine config node status

During the update of a  machine config pool (MCP), you can monitor the progress of individual nodes in case issues arise and you need to troubleshoot a node.

To see the status of the Machine Config Operator (MCO) updates to your cluster, use the following `oc` commands:

:FeatureName: Improved MCO state reporting
include::snippets/technology-preview.adoc[]

.Prerequisites
* You set `featureSet: TechPreviewNoUpgrade` in your `FeatureGate` custom resource (CR) to enable the feature set capability for your cluster.

.Procedure
. Get a summary of update statuses for all nodes in all machine config pools (MCP) by running the following command:
+
[source,terminal]
----
$ oc get machineconfignodes
----
+
.Example output
[source,text]
----
NAME                                       POOLNAME   DESIREDCONFIG                                      CURRENTCONFIG                                      UPDATED
ci-ln-mdb23yt-72292-kzdsg-master-0         master     rendered-master-f21b093d20f68a7c06f922ed3ea5fbc8   rendered-master-1abc053eec29e6c945670f39d6dc8afa   False
ci-ln-mdb23yt-72292-kzdsg-master-1         master     rendered-master-1abc053eec29e6c945670f39d6dc8afa   rendered-master-1abc053eec29e6c945670f39d6dc8afa   True
ci-ln-mdb23yt-72292-kzdsg-master-2         master     rendered-master-1abc053eec29e6c945670f39d6dc8afa   rendered-master-1abc053eec29e6c945670f39d6dc8afa   True
ci-ln-mdb23yt-72292-kzdsg-worker-a-gfqjr   worker     rendered-worker-d0130cd74e9e576d7ba78ce166272bfb   rendered-worker-8f61bf839898a4487c3b5263a430e94a   False
ci-ln-mdb23yt-72292-kzdsg-worker-b-gknq4   worker     rendered-worker-8f61bf839898a4487c3b5263a430e94a   rendered-worker-8f61bf839898a4487c3b5263a430e94a   True
ci-ln-mdb23yt-72292-kzdsg-worker-c-mffrx   worker     rendered-worker-8f61bf839898a4487c3b5263a430e94a   rendered-worker-8f61bf839898a4487c3b5263a430e94a   True
+
where:
+
NAME:: The name of the node.
POOLNAME:: The name of the MCP associated with that node.
DESIREDCONFIG:: The name of the new machine configuration that the node is updating to.
CURRENTCONFIG:: The name of the current machine configuration associated with that node. After the node is updated, the `CURRENTCONFIG` matches the `DESIREDCONFIG`. 
UPDATED:: The `True` status indicates that the MCO has applied the current machine config to that particular node. The `False` status indicates that the node is currently updating

. Check the update status of nodes in a specific machine config pool by running the following command:
+
[source,terminal]
----
$ oc get machineconfignodes $(oc get machineconfignodes -o json | jq -r '.items[]|select(.spec.pool.name=="<pool_name>")|.metadata.name') <1>
----
<1> The name of the pool is the `MachineConfigPool` object name.
+
.Example output
[source,text]
----
NAME                                       POOLNAME   DESIREDCONFIG                                      CURRENTCONFIG                                      UPDATED
ci-ln-g6dr34b-72292-g9btv-worker-a-sjh5r   worker     rendered-worker-d5534cb730e5e108905fc285c2a42b6c   rendered-worker-d5534cb730e5e108905fc285c2a42b6c   True
ci-ln-g6dr34b-72292-g9btv-worker-b-xthbz   worker     rendered-worker-d5534cb730e5e108905fc285c2a42b6c   rendered-worker-faf6b50218a8bbce21f1370866283de5   False
ci-ln-g6dr34b-72292-g9btv-worker-c-gnpd6   worker     rendered-worker-faf6b50218a8bbce21f1370866283de5   rendered-worker-faf6b50218a8bbce21f1370866283de5   True
----

. Check the update status of an individual node by running the following command:
+
[source,terminal]
----
$ oc describe machineconfignode/<node_name> <1>
----
<1> The name of the node is the `MachineConfigNode` object name.
+
.Example output
[source,text]
----
Name:         <node_name>
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  machineconfiguration.openshift.io/v1alpha1
Kind:         MachineConfigNode
Metadata:
  Creation Timestamp:  2023-10-17T13:08:58Z
  Generation:          1
  Resource Version:    49443
  UID:                 4bd758ab-2187-413c-ac42-882e61761b1d
Spec:
  Node Ref:
    Name:         <node_name>
  Pool:
    Name:         master
  ConfigVersion:
    Desired: rendered-worker-823ff8dc2b33bf444709ed7cd2b9855b <1>
Status:
# ...
    Last Transition Time:  2025-01-10T23:10:36Z
    Message:               Node ci-ln-mdb23yt-72292-kzdsg-master-0 Updated
    Reason:                Updated
    Status:                True
    Type:                  Updated
    Last Transition Time:  2025-01-10T23:10:36Z
    Message:               Action during update to rendered-master-8110974a5cea69dff5b263237b58abd8: UnCordoned node. The node is reporting Unschedulable = false
    Reason:                UpdateCompleteUncordoned
    Status:                False
    Type:                  Uncordoned
    Last Transition Time:  2025-01-10T22:46:25Z
    Message:               All is good
    Reason:                AsExpected
    Status:                False
    Type:                  PinnedImageSetsDegraded
  Config Version:
    Current:            rendered-master-8110974a5cea69dff5b263237b58abd8
    Desired:            rendered-master-8110974a5cea69dff5b263237b58abd8
  Observed Generation:  6
----
<1> The desired configuration specified in the `spec.configversion.desired` field updates immediately when a new configuration is detected on the node.
<2> The desired configuration specified in the `status.configversion.desired` field updates only when the new configuration is validated by the Machine Config Daemon (MCD). The MCD performs validation by checking the current phase of the update. If the update successfully passes the `UPDATEPREPARED` phase, then the status adds the new configuration.
