// Module included in the following assemblies:
//
// * logging/cluster-logging.adoc

ifeval::["{context}" == "virt-openshift-cluster-monitoring"]
:virt-logging:
endif::[]

[id="cluster-logging-about-components_{context}"]
= Cluster logging components 

The cluster logging components include a collector deployed to each node in the {product-title} cluster 
that collects all node and container logs and writes them to a log store. You can use a centralized web UI 
to create rich visualizations and dashboards with the aggregated data.

There are currently 3 different types of cluster logging components:

* collection - This is the component that collects logs from the node, formats them, and stores them in the log store. The current implementation is Fluentd.
* log store - This is where the logs are stored. The current implementation is Elasticsearch.
* visualization - This is the UI component used to view logs, graphs, charts, and so forth. The current implementation is Kibana.

ifndef::virt-logging[]
In this document, we may refer to log store or Elasticsearch, visualization or Kibana, curation or Curator, collection or Fluentd, interchangeably, except where noted.
endif::virt-logging[]

ifeval::["{context}" == "virt-openshift-cluster-monitoring"]
:!virt-logging:
endif::[]
