// Module included in the following assemblies:
//
// * logging/cluster-logging-viewing.adoc

[id="cluster-logging-viewing-logs-console_{context}"]
= Viewing pod logs in the web console 

You can view the pod log for various resources in the {product-title} web console. 

[NOTE]
====
Some resources, such as builds, do not have pods to query directly. Locate the *Logs* link on the *Details* page.
====

.Procedure 

To view pod logs:

. In the {product-title} console, navigate to *Workloads* -> *Pods* or navigate to the pod through the resource you want to investigate. 

. Select a project from the drop-down menu.

. Click one of the pods.

. Click *Logs*. 

By default, the logs read from the tail, or end, of the log. 

////
Rsyslog reads from the head, or beginning, of the log. 

You can configure Rsyslog to display the end of the log by setting the `RSYSLOG_JOURNAL_READ_FROM_TAIL` parameter in the Rsyslog daemon set:

[source,terminal]
----
$ oc set env ds/rsyslog RSYSLOG_JOURNAL_READ_FROM_TAIL=true
----
////
