// Module included in the following assemblies:
//
// * logging/cluster-logging-management.adoc

[id="cluster-logging-management-state-changing_{context}"]
= Changing the cluster logging management state

You must set the Cluster Logging Operator to the unmanaged state in order to modify the following components:

* the Curator CronJob,

* the Elasticsearch CR,

* the log collector DaemonSet.

* the Kibana CR.

[NOTE]
====
If you *must* perform configurations not described in the {product-title} documentation, you *must* set your Cluster Logging Operator or Elasticsearch Operator to *Unmanaged*. An unmanaged cluster logging environment is *not supported* and does not receive updates until you return cluster logging to Managed state. 
====

.Prerequisites

* The Cluster Logging Operator must be installed.

.Procedure

. Edit the Cluster Logging Custom Resource (CR) in the `openshift-logging` project:
+
----
$ oc edit ClusterLogging instance
----
+
[source,yaml]
----
apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogging"
metadata:
  name: "instance"

....

spec:
  managementState: "Unmanaged" <1>
---- 
<1> Specify the management state as `Managed` or `Unmanaged`.

. Edit the Elasticsearch Custom Resource (CR) in the `openshift-logging` project:
+
----
$ oc edit Elasticsearch elasticsearch
----
+
[source,yaml]
----
apiVersion: logging.openshift.io/v1
kind: Elasticsearch
metadata:
  name: elasticsearch


....

spec:
  managementState: "Unmanaged" <1>
----
<1> Specify the management state as `Managed` or `Unmanaged`.

[NOTE]
====
If you set the Elasticsearch Operator (EO) to unmanaged and leave the Cluster Logging Operator (CLO) as managed, the CLO will revert changes you make to the EO, as the EO is managed by the CLO.
====
