// Module included in the following assemblies:
//
// * logging/cluster-logging.adoc

[id="cluster-logging-about-logstore_{context}"]
= About the log store 

By default, {product-title} uses link:https://www.elastic.co/products/elasticsearch[Elasticsearch (ES)] to store log data. Optionally, you can use the log forwarding features to forward logs to external log stores using Fluentd protocols, syslsog protocols, or the {product-title} Log Forwarding API.

Elasticsearch organizes the log data from Fluentd into datastores, or _indices_, then subdivides each index into multiple pieces called _shards_, which it spreads across a set of Elasticsearch nodes in an Elasticsearch cluster. You can configure Elasticsearch to make copies of the shards, called _replicas_. Elasticsearch also spreads these replicas across the Elasticsearch nodes. The *ClusterLogging* Custom Resource allows you to specify the replication policy in the Custom Resource Definition (CRD) to provide data redundancy and resilience to failure. You can also define how long indices should be retained using a retention policy in the cluster logging CR.

[NOTE]
====
The number of primary shards for the index templates is equal to the number of Elasticsearch data nodes.
====

The Cluster Logging Operator and companion Elasticsearch Operator ensure that each Elasticsearch node is deployed using a unique Deployment that includes its own storage volume.
You can use a Cluster Logging Custom Resource (CR) to increase the number of Elasticsearch nodes, as needed.
Refer to link:https://www.elastic.co/guide/en/elasticsearch/guide/current/hardware.html[Elastic's documentation] for considerations involved in configuring storage.

[NOTE]
====
A highly-available Elasticsearch environment requires at least three Elasticsearch nodes,
each on a different host.
====

Role-based access control (RBAC) applied on the Elasticsearch indices enables the controlled access of the logs to the developers. Administrators can acccess all logs and developers can access only the logs in their projects.
