// Module included in the following assemblies:
//
// * logging/config/cluster-logging-collector.adoc

[id="cluster-logging-maintenance-and-support_{context}"]
= Unsupported configuration

The supported way of configuring {product-title} cluster logging is by configuring it using the options described in this documentumentation. *Do not use other configurations, as they are unsupported.* Configuration paradigms might change across {product-title} releases, and such cases can only be handled gracefully if all configuration possibilities are controlled. If you use configurations other than those described in this section, your changes will disappear because the cluster-monitoring-operator reconciles any differences. The operator reverses everything to the defined state by default and by design.

Explicitly unsupported cases include:

* Configuring default log rotation*. You cannot modify the default log rotation configuration.

* *Configuring the collected log location*. You cannot change the location of the log collector output file, by default `/var/log/fluentd/fluentd.log`.

* *Throttling log collection*. You cannot throttle down the rate at which the logs are read in by the log collector

* *Configuring log collection JSON parsing*. You cannot format log messages in *JSON*. 

* *Configuring the logging collector using environment variables*. You cannot use environment variables to modify the log collector.

* *Configuring how the log collector normalizes logs*. You cannot modify default log normalization.

* *Configuring Curator in scripted deployments*. You cannot configure log curation in scripted deployments.

* *Using the Curator Action file*. You cannot use *Curator* ConfigMap to modify the Curator *action* file.

* *Deleting Curator Indices*. You cannot configure log curation to delete indices.

