// Module included in the following assemblies:
//
// * logging/cluster-logging.adoc

ifeval::["{context}" == "virt-openshift-cluster-monitoring"]
:virt-logging:
endif::[]

[id="cluster-logging-about-components_{context}"]
= Cluster logging components 

The cluster logging components include a collector deployed to each node in the {product-title} cluster. 
thta collects all node and container logs and writes them to a logstore. You can use a centralized web UI 
to create rich visualizations and dashboards with the aggregated data.

There are currently 5 different types of cluster logging components:

* collection - This is the component that collects logs from the node, formats them, and stores them in the logStore. The current implementation is Fluentd.
* logStore - This is where the logs are stored. The current implementation is Elasticsearch.
* visualization - This is the UI component used to view logs, graphs, charts, and so forth. The current implementation is Kibana.
* curation - This is the component that trims logs by age. The current implementation is Curator.
* event routing - This is the component forwards {product-title} events to cluster logging. The current implementation is Event Router.

ifndef::virt-logging[]
In this document, we may refer to logStore or Elasticsearch, visualization or Kibana, curation or Curator, collection or Fluentd, interchangeably, except where noted.
endif::virt-logging[]

ifeval::["{context}" == "virt-openshift-cluster-monitoring"]
:!virt-logging:
endif::[]
