// Module included in the following assemblies:
//
// * machine_configuration/coreos-layering.adoc

:_mod-docs-content-type: PROCEDURE
[id="coreos-layering-configuring-on_{context}"]
= Using on-cluster layering to apply a custom layered image

To apply a custom layered image to your cluster by using the on-cluster build process, make a `MachineOSConfig` custom resource (CR) that specifies the following parameters: 

* the Containerfile to build
* the machine config pool to associate the build
* where the final image should be pushed and pulled from
* the push and pull secrets to use

When you create the object, the Machine Config Operator (MCO) 	creates a `MachineOSBuild` object and a `machine-os-builder` pod. The build process also creates transient objects, such as config maps, which are cleaned up after the build is complete.

When the build is complete, the MCO pushes the new custom layered image to your repository for use when deploying new nodes. You can see the digested image pull spec for the new custom layered image in the `MachineOSBuild` object and `machine-os-builder` pod.

You should not need to interact with these new objects or the `machine-os-builder` pod. However, you can use all of these resources for troubleshooting, if necessary.

You need a separate `MachineOSConfig` CR for each machine config pool where you want to use a custom layered image.

:FeatureName: On-cluster image layering
include::snippets/technology-preview.adoc[]
include::snippets//coreos-layering-configuring-on-pause.adoc[]

In the case of a build failure, for example due to network issues or an invalid secret, the MCO retries the build three times before the job fails. The MCO creates a different build pod for each build attempt. You can use the build pod log to troubleshoot any build failures. 

You can manually rebuild your custom layered image by either modify your `MachineOSConfig` object or applying an annotation to the `MachineOSConfig` object as discussed in the following section.

[discrete]
[id="coreos-layering-configuring-on-limitations_{context}"]
== On-cluster layering Technology Preview known limitations

Note the following limitations when working with the on-cluster layering feature:

* On-cluster layering is not supported on multi-architecture compute machines, single-node Openshift clusters, or disconnected clusters.
* If you scale-up a machine set that uses a custom layered image, the nodes will reboot two times. The first, when the node is initially created with the base image and a second time when the custom layered image is applied.
* Node disruption policies are not supported on nodes with a custom layered image. As a result the following configuration changes will cause a node reboot:
** Changes to the configuration files in the `/var` or `/etc` directory
** Adding or modifying a systemd service
** Changing SSH keys
** Removing mirroring rules from `ICSP`, `ITMS`, and `IDMS` objects
** Changing the trusted CA, by updating user-ca-bundle configmap in the `openshift-config` namespace
* The images used in creating custom layered images take up space in your push repository. Always be aware of the free space in your registry and prune the images as needed.

.Prerequisites

* You have enabled the `TechPreviewNoUpgrade` feature set by using the feature gates. For more information, see "Enabling features using feature gates".

<<<<<<< HEAD
* You have a copy of the pull secret in the `openshift-machine-config-operator` namespace that the MCO needs to pull the base operating system image. If you are using the global pull secret, the MCO automatically creates a copy when you first create a `MachineOSconfig` object.
=======
* You have a copy of the global pull secret in the `openshift-machine-config-operator` namespace that the MCO needs to pull the base operating system image.
>>>>>>> further edits from testing

* You have the push secret that the MCO needs to push the new custom layered image to your registry.

* You have a pull secret that your nodes need to pull the new custom layered image from your registry. This should be a different secret than the one used to push the image to the repository.

* You are familiar with how to configure a Containerfile. Instructions on how to create a Containerfile are beyond the scope of this documentation.

* Optional: You have a separate machine config pool for the nodes where you want to apply the custom layered image.

.Procedure

. Create a `MachineOSconfig` object:

.. Create a YAML file similar to the following:
+
[source,terminal]
----
apiVersion: machineconfiguration.openshift.io/v1alpha1
kind: MachineOSConfig
metadata:
  name: layered
spec:
  machineConfigPool:
    name: <mcp_name> <1>
  buildInputs:
<<<<<<< HEAD
    containerFile: # <2>
    - containerfileArch: noarch <3>
      content: |-
        FROM configs AS final <4>
        RUN dnf install -y cowsay && \
         dnf clean all && \
         ostree container commit
    imageBuilder: # <5>
      imageBuilderType: PodImageBuilder
    baseImagePullSecret: # <6>
      name: global-pull-secret-copy
    renderedImagePushspec: image-registry.openshift-image-registry.svc:5000/openshift/os-image:latest  # <7>
    renderedImagePushSecret: # <8>
      name: builder-dockercfg-7lzwl
  buildOutputs: # <9>
    currentImagePullSecret:
      name: builder-dockercfg-7lzwl
----
<1> Specifies the machine config pool to deploy the custom layered image.
<2> Specifies the Containerfile to configure the custom layered image. You can specify multiple build stages in the Containerfile.
<3> Specifies the architecture of the image to be built. You must set this parameter to `noarch`.
<4> Specifies the build stage as final. This field is required and applies to the last image in the build.
<5> Specifies the name of the image builder to use. You must set this parameter to `PodImageBuilder`.
<6> Specifies the name of the pull secret that the MCO needs in order to pull the base operating system image from the registry.
<7> Specifies the image registry to push the newly-built custom layered image to. This can be any registry that your cluster has access to. This example uses the internal {product-title} registry.
<8> Specifies the name of the push secret that the MCO needs in order to push the newly-built custom layered image to the registry.
<9> Specifies the secret required by the image registry that the nodes need in order to pull the newly-built custom layered image. This should be a different secret than the one used to push the image to your repository.
=======
    containerFile: <2>
    - containerfileArch: noarch <3>
      content: |-
        FROM configs AS final
        RUN rpm-ostree install tree && \
          ostree container commit
    imageBuilder: <4>
      imageBuilderType: PodImageBuilder
    baseImagePullSecret: <5>
      name: global-pull-secret-copy
    renderedImagePushspec: image-registry.openshift-image-registry.svc:5000/openshift-machine-config-operator/os-images:latest <6>
    renderedImagePushSecret: <7>
      name: builder-dockercfg-7lzwl
  buildOutputs: <8>
    currentImagePullSecret:
      name: builder-dockercfg-7lzwl
----
<1> Specifies the name of the machine config pool associated with the nodes where you want to deploy the custom layered image.
<2> Specifies the Containerfile to configure the custom layered image.
<3> Specifies the architecture this containerfile is to be built for. This must be `noarch`, which defines a Containerfile that can be applied to any architecture. 
<4> Specifies the name of the image builder to use. This must be `PodImageBuilder`.
<5> Specifies the name of the pull secret that the MCO needs to pull the base operating system image from the registry. By default, the global pull secret is used. 
<6> Specifies the image registry to push the newly-built custom layered image to. This can be any registry that your cluster has access to in the the `host[:port][/namespace]/name` or `svc_name.namespace.svc[:port]/repository/name:<tag>` format. This example uses the internal {product-title} registry. You can specify a mirror registry if you cluster is properly configured to use a mirror registry.
<7> Specifies the name of the push secret that the MCO needs to push the newly-built custom layered image to that registry.
<8> Specifies the name of the push secret that the MCO needs to push the newly-built custom layered image to that registry.
>>>>>>> revert changes

.. Create the `MachineOSConfig` object:
+
[source,terminal]
----
$ oc create -f <file_name>.yaml
----

. If necessary, when the `MachineOSBuild` object has been created and is in the `READY` state, modify the node spec for the nodes where you want to use the new custom layered image:
+
.. Check that the `MachineOSBuild` object is `READY`. When the `SUCCEEDED` value is `True`, the build is complete.
+
[source,terminal]
----
$ oc get machineosbuild
----
+
.Example output showing that the `MachineOSBuild` object is ready
[source,terminal]
----
NAME                                                                PREPARED   BUILDING   SUCCEEDED   INTERRUPTED   FAILED
layered-rendered-layered-ad5a3cad36303c363cf458ab0524e7c0-builder   False      False      True        False         False
----

.. Edit the nodes where you want to deploy the custom layered image by adding a label for the machine config pool you specified in the `MachineOSConfig` object:
+
[source,terminal]
----
$ oc label node <node_name> 'node-role.kubernetes.io/<mcp_name>='
----
+
--
where:

node-role.kubernetes.io/<mcp_name>=:: Specifies a node selector that identifies the nodes to deploy the custom layered image. 
--
+
When you save the changes, the MCO drains, cordons, and reboots the nodes. After the reboot, the node uses the new custom layered image.

.Verification

. Verify that the new pods are ready by running the following command:
+
[source,terminal]
----
$ oc get pods -n openshift-machine-config-operator
----
+
.Example output
[source,terminal]
----
NAME                                                              READY   STATUS    RESTARTS   AGE
build-rendered-layered-ad5a3cad36303c363cf458ab0524e7c0           2/2     Running   0          2m40s # <1>
# ...
machine-os-builder-6fb66cfb99-zcpvq                               1/1     Running   0          2m42s # <2>
----
<1> This is the build pod where the custom layered image is building. The MCO removes this pod after the build is complete.
<2> This pod can be used for troubleshooting.

. Verify that the `MachineOSConfig` object contains a reference to the new custom layered image by running the following command:
+
[source,terminal]
----
$ oc get machineosbuilds
----
+
.Example output
[source,terminal]
----
<<<<<<< HEAD
NAME                                                                PREPARED   BUILDING   SUCCEEDED   INTERRUPTED   FAILED
layered-rendered-layered-ef6460613affe503b530047a11b28710-builder   False      True       False       False         False
=======
Name:         layered
Namespace:    
Labels:       <none>
Annotations:  machineconfiguration.openshift.io/current-machine-os-build: layered-1b0d98b4e70535aacdbb5b601924516f
API Version:  machineconfiguration.openshift.io/v1
Kind:         MachineOSConfig
Metadata:
  Creation Timestamp:  2025-01-29T17:18:26Z
  Generation:          1
  Resource Version:    67952
  UID:                 7ad6a965-24c8-486b-9c26-c4bfe2a9704b
Spec:
  Build Inputs:
    Base Image Pull Secret:
      Name:  global-pull-secret-copy
    Container File:
      Containerfile Arch:  noarch
      Content:             FROM configs AS final
RUN rpm-ostree install tree && \
  ostree container commit
    Image Builder:
      Image Builder Type:  PodImageBuilder
    Rendered Image Push Secret:
      Name:                   builder-dockercfg-k85lt
    Rendered Image Pushspec:  image-registry.openshift-image-registry.svc:5000/openshift-machine-config-operator/os-images:latest
  Build Outputs:
    Current Image Pull Secret:
      Name:  builder-dockercfg-k85lt
  Machine Config Pool:
    Name:  layered
 # ...
Status:
  Current Image Pullspec:  image-registry.openshift-image-registry.svc:5000/openshift-machine-config-operator/os-images@sha256:efe5ca166c2b0d75c76958fac7c259a33f9c897c38164f7c7e6e6abca940b28e
  Observed Generation:     1
# ...
>>>>>>> further edits from testing
----

. Verify that the `MachineOSBuild` object contains a reference to the new custom layered image by running the following command:
+
[source,terminal]
----
$ oc describe machineosbuild <object_name>
----
+
.Example output
[source,yaml]
----
<<<<<<< HEAD
apiVersion: machineconfiguration.openshift.io/v1alpha1
kind: MachineOSBuild
metadata:
  name: layered-rendered-layered-ad5a3cad36303c363cf458ab0524e7c0-builder
spec:
  desiredConfig:
    name: rendered-layered-ad5a3cad36303c363cf458ab0524e7c0
  machineOSConfig:
    name: layered <1>
  renderedImagePushspec: image-registry.openshift-image-registry.svc:5000/openshift-machine-config-operator/os-image:latest
# ...
status:
  conditions:
    - lastTransitionTime: "2024-05-21T20:25:06Z"
      message: Build Ready
      reason: Ready
      status: "True"
      type: Succeeded
  finalImagePullspec: image-registry.openshift-image-registry.svc:5000/openshift-machine-config-operator/os-image@sha256:f636fa5b504e92e6faa22ecd71a60b089dab72200f3d130c68dfec07148d11cd # <1>
=======
Name:         layered-1b0d98b4e70535aacdbb5b601924516f
Namespace:    
Labels:       machineconfiguration.openshift.io/machine-os-config=layered
              machineconfiguration.openshift.io/rendered-machine-config=rendered-layered-f48d821c77690669a307a333f1000ee0
              machineconfiguration.openshift.io/target-machine-config-pool=layered
Annotations:  <none>
API Version:  machineconfiguration.openshift.io/v1
Kind:         MachineOSBuild
# ...
Spec:
  Config Generation:  1
  Desired Config:
    Name:  rendered-layered-708c652868f7597eaa1e2622edc366ef
  Machine OS Config:
    Name:                   layered
  Rendered Image Pushspec:  image-registry.openshift-image-registry.svc:5000/openshift-machine-config-operator/os-images:layered-ab22a5ff77a42f81044aaa5abea65aeb
  Version:                  1
Status:
  Build End:    2025-01-29T17:34:08Z
  Build Start:  2025-01-29T17:18:47Z
  Builder Reference:
    Build Pod:
      Group:             
      Name:              build-layered-ab22a5ff77a42f81044aaa5abea65aeb
      Namespace:         openshift-machine-config-operator
      Resource:          68802
    Image Builder Type:  PodImageBuilder
# ... 
    Last Transition Time:  2025-01-31T17:32:47Z
    Message:               Build Ready
    Reason:                Ready
    Status:                True
    Type:                  Succeeded
  Final Image Pullspec:    image-registry.openshift-image-registry.svc:5000/openshift-machine-config-operator/os-images@sha256:efe5ca166c2b0d75c76958fac7c259a33f9c897c38164f7c7e6e6abca940b28e <1>
>>>>>>> further edits from testing
----
<1> Digested image pull spec for the new custom layered image.

. Verify that the appropriate nodes are using the new custom layered image:

.. Start a debug session as root for a control plane node:
+
[source,terminal]
----
$ oc debug node/<node_name>
----

.. Set `/host` as the root directory within the debug shell:
+
[source,terminal]
----
sh-4.4# chroot /host
----

.. Run the `rpm-ostree status` command to view that the custom layered image is in use:
+
[source,terminal]
----
sh-5.1# rpm-ostree status
----
+
.Example output
[source,terminal]
----
# ...
Deployments:
* ostree-unverified-registry:image-registry.openshift-image-registry.svc:5000/openshift-machine-config-operator/os-images@sha256:efe5ca166c2b0d75c76958fac7c259a33f9c897c38164f7c7e6e6abca940b28e
                   Digest: sha256:efe5ca166c2b0d75c76958fac7c259a33f9c897c38164f7c7e6e6abca940b28e
                  Version: 418.94.202501300706-0 (2025-01-31T17:32:10Z)
----
<1> Digested image pull spec for the new custom layered image.
