// Module included in the following assemblies:
//
// * machine_configuration/coreos-layering.adoc

:_mod-docs-content-type: PROCEDURE
[id="coreos-layering-configuring-on-extensions_{context}"]
= Installing extensions into an on-cluster custom layered image

You can install :op-system-first: extensions into your on-cluster custom layered image by creating a machine config that lists the extensions that you want to install. The Machine Config Operator (MCO) installs the extensions into the nodes associated with a specific machine config pool (MCP).

include::snippets/mco-rhcos-extensions-info.adoc[]

.Prerequisites

* You have opted-in to on-cluster layering by creating a `MachineOSConfig` object.

.Procedure

. Create a YAML file for the custom machine config pool similar to the following example: 
+
[source,terminal]
----
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: layered
  name: 80-worker-extensions
spec:
  config:
    ignition:
      version: 3.2.0
  extensions: <1>
    - usbguard
    - kerberos
----
<1> List the :op-system-first: extensions that you want to install.

. Create the MCP object:
+
[source,terminal]
----
$ oc create -f <file_name>.yaml
----

.Verification

. When the node is back in the `Ready` state, check that the extensions were installed:

.. Open an `oc debug` session to the node by running the following command:
+
[source,terminal]
----
$ oc debug node/<node_name>
----

.. Set `/host` as the root directory within the debug shell by running the following command:
+
[source,terminal]
----
sh-5.1# chroot /host
----

.. Use an appropriate command to verify that the extension is installed. For example:
+
[source,terminal]
----
sh-5.1# rpm -qa |grep usbguard
----
+
. Example output
[source,terminal]
----
usbguard-selinux-1.0.0-15.el9.noarch
usbguard-1.0.0-15.el9.x86_64
----

///
.. Use the appropriate commands to start the extension and view the status. For example:
+
[source,terminal]
----
sh-5.1# systemctl enable --now usbguard
----
+
[source,terminal]
----
sh-5.1# systemctl status usbguard
----
+
. Example output
[source,terminal]
----
● usbguard.service - USBGuard daemon
     Loaded: loaded (/usr/lib/systemd/system/usbguard.service; enabled; preset: disabled)
     Active: active (running) since Thu 2025-01-30 17:57:45 UTC; 1s ago
       Docs: man:usbguard-daemon(8)
    Process: 46338 ExecStart=/usr/sbin/usbguard-daemon -f -s -K -c /etc/usbguard/usbguard-daemon.conf (code=exited, status=0/SUCCESS)
   Main PID: 46340 (usbguard-daemon)
      Tasks: 3 (limit: 99986)
     Memory: 3.0M
        CPU: 101ms
     CGroup: /system.slice/usbguard.service
             └─46340 /usr/sbin/usbguard-daemon -f -s -K -c /etc/usbguard/usbguard-daemon.conf

Jan 30 17:57:44 ip-10-0-4-252 systemd[1]: Starting USBGuard daemon...
Jan 30 17:57:45 ip-10-0-4-252 systemd[1]: Started USBGuard daemon.
----
////
