// Module included in the following assemblies:
//
// * machine_configuration/coreos-layering.adoc

:_mod-docs-content-type: PROCEDURE
[id="coreos-layering-configuring-on-extensions_{context}"]
= Installing extensions into an on-cluster custom layered image

You can install :op-system-first: extensions into your on-cluster custom layered image by creating a machine config that lists the extensions that you want to install. The Machine Config Operator (MCO) installs the extensions into the nodes associated with a specific machine config pool (MCP).

include::snippets/mco-rhcos-extensions-info.adoc[]

After you make the change, the MCO reboots the nodes associated with the specified machine config pool.

include::snippets//coreos-layering-configuring-on-pause.adoc[]

.Prerequisites

* You have opted-in to on-cluster layering by creating a `MachineOSConfig` object.

.Procedure

. Create a YAML file for the custom machine config pool similar to the following example: 
+
[source,terminal]
----
apiVersion: machineconfiguration.openshift.io/v1alpha1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: layered <1>
  name: 80-worker-extensions
spec:
  config:
    ignition:
      version: 3.2.0
  extensions: <2>
    - usbguard
    - kerberos
----
<1> Specifies the machine config pool to apply to `MachineConfig` object.
<2> Lists the :op-system-first: extensions that you want to install.

. Create the MCP object:
+
[source,terminal]
----
$ oc create -f <file_name>.yaml
----

.Verification

. When the associates machine config pool is updated, check that the extensions were installed:

.. Open an `oc debug` session to the node by running the following command:
+
[source,terminal]
----
$ oc debug node/<node_name>
----

.. Set `/host` as the root directory within the debug shell by running the following command:
+
[source,terminal]
----
sh-5.1# chroot /host
----

.. Use an appropriate command to verify that the extensions were installed. The following example shows that the usbguard extension was installed:
+
[source,terminal]
----
sh-5.1# rpm -qa |grep usbguard
----
+
.Example output
[source,terminal]
----
usbguard-selinux-1.0.0-15.el9.noarch
usbguard-1.0.0-15.el9.x86_64
----
