:_mod-docs-content-type: REFERENCE
[id="hcp-release-notes-new-features_{context}"]
= New features and enhancements

This release adds improvements related to the following components and concepts:

////
Instructions: Add entries in the following format:

Item description::
+
Detailed information.
////

ARM64 compute nodes now supported with 64-bit x86 control plane::
+
In this release, ARM64 compute nodes are supported with a 64-bit x86 control plane on bare-metal deployments of {hcp}. For more information about multi-architecture support for {hcp}, see the xref:../hosted_control_planes/hcp-prepare/hcp-requirements.adoc#hcp-support-matrix_hcp-requirements[Support matrix for {hcp}].

Monitor connectivity between the control plane and the data plane::
+
In this release, cluster service providers can monitor network activity between a hosted control plane and the compute nodes in a data plane by using the `DataPlaneConnectionAvailable` condition. For more information, see xref:../hosted_control_planes/hcp-observability.adoc#hcp-connect-data-plane_hcp-observability[Connectivity monitoring from the control plane to the data plane].