// Module included in the following assemblies:
//
// * machine_configuration/machine-config-pools-about.adoc

:_mod-docs-content-type: PROCEDURE
[id="machine-config-pools-custom-configure_{context}"]
= Creating a custom machine config pool

To create a custom machine config pool, you create a `MachineConfigPool` object that contains a custom role as the `machineConfigSelector`.

The following procedure creates a custom machine config pool named `infra` that is also associated with the `worker` machine config pool.

.Procedure

. Create a YAML file that defines your custom machine config pool:
+
[source,yaml]
----
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: infra <1>
spec:
  machineConfigSelector:
    matchExpressions:
      - {key: machineconfiguration.openshift.io/role, operator: In, values: [worker,infra]} <2>
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/infra: ""
----
<1> Specifies a descriptive name for the MCP.
<2> Specifies a label for the custom MCP. You must also include `worker` label as a value, even if you remove the `worker` label from your custom node.

. Create the CR  by running the following command:
+
[source,terminal]
----
$ oc create -f <file_name>.yaml
----

.Verification

* View the new machine config pool by using the following command:
+
[source,terminal]
----
$ oc get mcp
----
+
.Example output
[source,terminal]
----
NAME     CONFIG                                             UPDATED   UPDATING   DEGRADED   MACHINECOUNT   READYMACHINECOUNT   UPDATEDMACHINECOUNT   DEGRADEDMACHINECOUNT   AGE
infra    rendered-infra-b5250cb9e8c4a0b9d3e16da185ba4bad    True      False      True       0              0                   0                     0                      15s <1>
master   rendered-master-b1d4b6196a18869d63518e57b8b335d1   True      False      False      3              3                   3                     0                      156m
worker   rendered-worker-c48ef626ff01f0a445979a4245dc7bdd   True      False      False      3              3                   3                     0                      156m
----
<1> This is the custom machine config pool.
+
Creating a new machine config pool also creates an associated machine configuration, listed under `CONFIG`, here `rendered-infra-b5250cb9e8c4a0b9d3e16da185ba4bad`. Note that there are no nodes associated with the new machine config pool.

* View the new machine config by using the following command:
+
[source,terminal]
----
$ oc get mc
----
+
.Example output
[source,terminal]
----
NAME                                               GENERATEDBYCONTROLLER                      IGNITIONVERSION   AGE
00-master                                          40d03dc1376995a2d65e10af48287dc8d2b2012e   3.4.0             157m
00-worker                                          40d03dc1376995a2d65e10af48287dc8d2b2012e   3.4.0             157m
# ...
rendered-infra-b5250cb9e8c4a0b9d3e16da185ba4bad    40d03dc1376995a2d65e10af48287dc8d2b2012e   3.4.0             73s <1>
# ...
----
<1> This is custom machine config to be applied to the nodes in the new machine config pool.
