// Module included in the following assemblies:
//
// * machine_configuration/machine-config-pools-about.adoc

:_mod-docs-content-type: PROCEDURE
[id="machine-config-pools-custom-modify_{context}"]
= Modifying a custom machine config pool

To deploy changes to the nodes in a custom pool, create a `MachineConfig` object that uses the custom pool as the label. For example the following procedure disables `chronyd`.

Changes made to the custom machine config are not applied to the `worker` machine config. However, if you make a change to the `worker` machine config pool, the change is applied to the `worker` and custom machine config pools and their associated nodes.

.Procedure

. Create the `MachineConfig` CR that disables `chronyd` for the specified node role.
+
[source,yaml]
----
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: <node_role> <1>
  name: disable-chronyd
spec:
  config:
    ignition:
      version: 3.2.0
    systemd:
      units:
        - contents: |
            [Unit]
            Description=NTP client/server
            Documentation=man:chronyd(8) man:chrony.conf(5)
            After=ntpdate.service sntp.service ntpd.service
            Conflicts=ntpd.service systemd-timesyncd.service
            ConditionCapability=CAP_SYS_TIME
            [Service]
            Type=forking
            PIDFile=/run/chrony/chronyd.pid
            EnvironmentFile=-/etc/sysconfig/chronyd
            ExecStart=/usr/sbin/chronyd $OPTIONS
            ExecStartPost=/usr/libexec/chrony-helper update-daemon
            PrivateTmp=yes
            ProtectHome=yes
            ProtectSystem=full
            [Install]
            WantedBy=multi-user.target
          enabled: false
          name: "chronyd.service"
----
<1> Node role where you want to disable `chronyd`, for example, `master`.

. Create the `MachineConfig` CR by running the following command:
+
[source,terminal]
----
$ oc create -f disable-chronyd.yaml
----

.Verification

* You can see that the machine config pool is being updated by using the following commands:
+
[source,terminal]
----
$ oc get mcp
----
+
.Example output
[source,terminal]
----
NAME     CONFIG                                             UPDATED   UPDATING   DEGRADED   MACHINECOUNT   READYMACHINECOUNT   UPDATEDMACHINECOUNT   DEGRADEDMACHINECOUNT   AGE
infra    rendered-custom-11f6e3ee8704373add6d3c3d8399b3fa   False     True       False      1              1                   1                     0                      11m
master   rendered-master-94cafd2f05c7cd9a3fce4877e699fa45   True      False      False      3              3                   3                     0                      119m
worker   rendered-worker-93ac02b5fc2e2526b8b15758df3d8472   True      False      False      2              2                   2                     0                      119m
----
+
[source,terminal]
----
$ oc get mc
----
+
.Example output
[source,terminal]
----
#...
disable-chronyd                                                                               3.2.0             83s <1>
rendered-infra-0607ee792b74e1521379d7e7c6038037    4a8a503c3a969e948fb4dbeab19a5d3f0727d1c6   3.5.0             78s <2>
#...
----
<1> New machine config that you created.
<2> Rendered machine config created by the MCO to integrate the changes introduced by your machine config. The rendered machine config is applied to the nodes in the machine config pool.

* You can see that the node in that machine config pool is being updated by using the following commands:
+
.Example output
[source,terminal]
----
NAME                                       STATUS                         ROLES                  AGE    VERSION
ci-ln-4wib8b2-72292-qfjz6-master-0         Ready                          control-plane,master   116m   v1.34.2
ci-ln-4wib8b2-72292-qfjz6-master-1         Ready                          control-plane,master   117m   v1.34.2
ci-ln-4wib8b2-72292-qfjz6-master-2         Ready                          control-plane,master   117m   v1.34.2
ci-ln-4wib8b2-72292-qfjz6-worker-a-f4mf5   NotReady,SchedulingDisabled    infra                  97m    v1.34.2 <1>
ci-ln-4wib8b2-72292-qfjz6-worker-b-6z4rx   Ready                          worker                 97m    v1.34.2
ci-ln-4wib8b2-72292-qfjz6-worker-c-h6khl   Ready                          worker                 97m    v1.34.2
----
<1> Scheduling is disabled on the node as this change is being applied. Different changes yeild different states on the node.

* You can see that the new rendered machine config has been applied to the node by using a the following command:
+
[source,terminal]
----
$ oc get machineconfignode
----
+
.Example output
[source,terminal]
----
NAME                                       POOLNAME   DESIREDCONFIG                                      CURRENTCONFIG                                      UPDATED   AGE
ci-ln-4wib8b2-72292-qfjz6-master-0         master     rendered-master-166650f7af20cd3169d980c7a1aee6c0   rendered-master-166650f7af20cd3169d980c7a1aee6c0   True      125m
ci-ln-4wib8b2-72292-qfjz6-master-1         master     rendered-master-166650f7af20cd3169d980c7a1aee6c0   rendered-master-166650f7af20cd3169d980c7a1aee6c0   True      125m
ci-ln-4wib8b2-72292-qfjz6-master-2         master     rendered-master-166650f7af20cd3169d980c7a1aee6c0   rendered-master-166650f7af20cd3169d980c7a1aee6c0   True      125m
ci-ln-4wib8b2-72292-qfjz6-worker-a-f4mf5   infra      rendered-infra-0607ee792b74e1521379d7e7c6038037    rendered-infra-0607ee792b74e1521379d7e7c6038037    True      109m <1>
ci-ln-4wib8b2-72292-qfjz6-worker-b-6z4rx   worker     rendered-worker-2dba3548b2ed650f561a9185c090dcf9   rendered-worker-2dba3548b2ed650f561a9185c090dcf9   True      109m
ci-ln-4wib8b2-72292-qfjz6-worker-c-h6khl   worker     rendered-worker-2dba3548b2ed650f561a9185c090dcf9   rendered-worker-2dba3548b2ed650f561a9185c090dcf9   True      109m
----
<1> The node in the `infra` machine config pool is now using the new rendered machine config.

