// Module included in the following assemblies:
//
// * machine_management/deploying-machine-health-checks.adoc
// * post_installation_configuration/node-tasks.adoc


[id="machine-health-checks-resource_{context}"]
= Sample `MachineHealthCheck` resource

The `MachineHealthCheck` resource resembles one of the following YAML files:

.`MachineHealthCheck` for bare metal
[source,yaml]
----
apiVersion: machine.openshift.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: example <1>
  namespace: openshift-machine-api
  annotations:
    machine.openshift.io/remediation-strategy: external-baremetal <2>
spec:
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-machine-role: <role> <3>
      machine.openshift.io/cluster-api-machine-type: <role> <3>
      machine.openshift.io/cluster-api-machineset: <cluster_name>-<label>-<zone> <4>
  unhealthyConditions:
  - type:    "Ready"
    timeout: "300s" <5>
    status: "False"
  - type:    "Ready"
    timeout: "300s" <5>
    status: "Unknown"
  maxUnhealthy: "40%" <6>
  nodeStartupTimeout: "10m" <7>
----

<1> Specify the name of the machine health check to deploy.
<2> For bare metal clusters, you must include the `machine.openshift.io/remediation-strategy: external-baremetal` annotation in the `annotations` section to enable power-cycle remediation. With this remediation strategy, unhealthy hosts are rebooted instead of removed from the cluster.
<3> Specify a label for the machine pool that you want to check.
<4> Specify the machine set to track in `<cluster_name>-<label>-<zone>` format. For example, `prod-node-us-east-1a`.
<5> Specify the timeout duration for a node condition. If a condition is met for the duration of the timeout, the machine will be remediated. Long timeouts can result in long periods of downtime for a workload on an unhealthy machine.
<6> Specify the amount of unhealthy machines allowed in the targeted pool. This can be set as a percentage or an integer.
<7> Specify the timeout duration that a machine health check must wait for a node to join the cluster before a machine is determined to be unhealthy.

[NOTE]
====
The `matchLabels` are examples only; you must map your machine groups based on your specific needs.
====

.`MachineHealthCheck` for all other installation types
[source,yaml]
----
apiVersion: machine.openshift.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: example <1>
  namespace: openshift-machine-api
spec:
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-machine-role: <role> <2>
      machine.openshift.io/cluster-api-machine-type: <role> <2>
      machine.openshift.io/cluster-api-machineset: <cluster_name>-<label>-<zone> <3>
  unhealthyConditions:
  - type:    "Ready" <4>
    timeout: "300s" <5>
    status: "False"
  - type:    "Ready"
    timeout: "300s"
    status: "Unknown"
  - type:    "MemoryPressure"
    timeout: "300s" 
    status: "True"
  - type:    "PIDPressure"
    timeout: "300s" 
    status: "True"
  - type:    "OutofDisk"
    timeout: "300s" 
    status: "True"
  - type:    "NetworkUnavailable"
    timeout: "300s"
    status: "True"
  - type:    "NotReady"
    timeout: "300s"
    status: "True"
  - type:    "SchedulingDisabled"
    timeout: "300s"
    status: "True"
  maxUnhealthy: "40%" <6>
  nodeStartupTimeout: "10m" <7>
----
<1> Specify the name of the machine health check to deploy.
<2> Specify a label for the machine pool that you want to check.
<3> Specify the machine set to track in `<cluster_name>-<label>-<zone>` format. For example, `prod-node-us-east-1a`.
<4> Specify the node conditions to check for. See the node conditions in the table below.
<5> Specify the timeout duration for a node condition. If a condition is met for the duration of the timeout, the machine will be remediated. Long timeouts can result in long periods of downtime for the workload on an unhealthy machine.
<6> Specify the amount of unhealthy machines allowed in the targeted pool. This can be set as a percentage or an integer.
<7> Specify the timeout duration that a machine health check must wait for a node to join the cluster before a machine is determined to be unhealthy.

[NOTE]
====
The `matchLabels` are examples only; you must map your machine groups based on your specific needs.
====

The following table lists and defines the node conditions you can use with machine health checks.

[discrete]
[id="machine-health-checks-resource-conditions"]
.Node Conditions
[cols="3a,8a",options="header"]
|===

|Condition |Description

|`Ready`
|If `true` the node is healthy and ready to accept pods. If `false` the node is not healthy and is not accepting pods. If `unknown`, the node controller has not received a heartbeat from the node for the `node-monitor-grace-period` (the default is 40 seconds).

|`DiskPressure`
|If `true` the disk capacity is low.

|`MemoryPressure`
|If `true` the node memory is low.

|`PIDPressure`
|If `true` there are too many processes on the node.

|`OutOfDisk`
|If `true`, the node has insufficient free space on the node for adding new pods.

|`NetworkUnavailable`
| If `true` the network for the node is not correctly configured.

|`NotReady`
|If `true` one of the underlying components, such as the container runtime or network, is experiencing issues or is not yet configured.

|`SchedulingDisabled`
|Pods cannot be scheduled for placement on the node.

|===


[id="machine-health-checks-short-circuiting_{context}"]
== Short-circuiting machine health check remediation

Short circuiting ensures that machine health checks remediate machines only when the cluster is healthy.
Short-circuiting is configured through the `maxUnhealthy` field in the `MachineHealthCheck` resource.

If the user defines a value for the `maxUnhealthy` field,
before remediating any machines, the `MachineHealthCheck` compares the value of `maxUnhealthy`
with the number of machines within its target pool that it has determined to be unhealthy.
Remediation is not performed if the number of unhealthy machines exceeds the `maxUnhealthy` limit.

[IMPORTANT]
====
If `maxUnhealthy` is not set, the value defaults to `100%` and the machines are remediated regardless of the state of the cluster.
====

The `maxUnhealthy` field can be set as either an integer or percentage.
There are different remediation implementations depending on the `maxUnhealthy` value.

=== Setting `maxUnhealthy` by using an absolute value

If `maxUnhealthy` is set to `2`:

* Remediation will be performed if 2 or fewer nodes are unhealthy
* Remediation will not be performed if 3 or more nodes are unhealthy

These values are independent of how many machines are being checked by the machine health check.

=== Setting `maxUnhealthy` by using percentages

If `maxUnhealthy` is set to `40%` and there are 25 machines being checked:

* Remediation will be performed if 10 or fewer nodes are unhealthy
* Remediation will not be performed if 11 or more nodes are unhealthy

If `maxUnhealthy` is set to `40%` and there are 6 machines being checked:

* Remediation will be performed if 2 or fewer nodes are unhealthy
* Remediation will not be performed if 3 or more nodes are unhealthy

[NOTE]
====
The allowed number of machines is rounded down when the percentage of `maxUnhealthy` machines that are checked is not a whole number.
====

