// Module included in the following assemblies:
//
// * machine-configuration/mco-update-boot-images.adoc
// * nodes/nodes/nodes-update-boot-images.adoc

:_mod-docs-content-type: PROCEDURE
[id="mco-update-boot-skew-mgmt-configuring.adoc_{context}"]
= Configuring boot image skew enforcement

[role="_abstract"]
You can configure the current boot image skew enforcement mode that the Machine Config Operator (MCO) uses. By configuring the boot image skew enforcement level, you specify the current boot image version used in the cluster, which the MCO uses to determine boot image skew compliance in your cluster.

Alternatively, you can disable boot image skew enforcement by setting the `mode` to `None`. When disabled, the MCO does not monitor for boot image skew and older boot images could be used, possibly introducing compatibility issues on new nodes.

In {product-title} 4.22, the automatic mode is available only for {aws-short}, {gcp-short}, {azure-short}, and {vmw-short} clusters and is the default for these platforms. All other platforms default to manual mode. If you modify a cluster from automatic mode to manual or none, you can revert a cluster to automatic mode only by removing the `bootImageSkewEnforcement` stanza from the `MachineConfiguration` object.

.Prerequisites

* You enabled the required Technology Preview features for your cluster by editing the `FeatureGate` CR named `cluster`.
+
[WARNING]
====
Enabling the `TechPreviewNoUpgrade` feature set on your cluster cannot be undone and prevents minor version updates. You should not enable this feature set on production clusters.
====

.Procedure

. For manual mode, you can obtain the current boot image on a node by using the following command:
+
[source,terminal]
----
$ oc debug node/<new-node> -- chroot /host cat /sysroot/.coreos-aleph-version.json
----
+
.Example output
[source,terminal]
----
# ...
    "ref": "docker://ostree-image-signed:oci-archive:/rhcos-9.6.20251023-0-ostree.x86_64.ociarchive",
    "version": "9.6.20251023-0"
----

. Specify the boot image skew enforcement mode and set the boot image version as needed:
+
[source,yaml]
----
apiVersion: operator.openshift.io/v1
kind: MachineConfiguration
metadata:
  name: cluster
spec:
# ...
  bootImageSkewEnforcement:
    mode: Manual
    manual:
      mode: RHCOSVersion
      rhcosVersion: 9.0.20251023-0
# ...
----
where:

`spec.bootImageSkewEnforcement.mode`:: Specifies the boot image management mode, one of the following values:
+
--
* `Manual`. The cluster admin is responsible to manually configure the boot image version based on the `ocpVersion` or `rhcosVersion` parameter. You must specify the `spec.bootImageSkewEnforcement.manual` parameters.
* `None`. Boot image management is disabled. You do not need to specify the `spec.bootImageSkewEnforcement.manual` parameters.
--
+
`spec.bootImageSkewEnforcement.manual`:: For the `Manual` mode, specifies that the minimum boot image is based on the specific {product-title} or {op-system} version. This example configures an {op-system} version. You must include the following parameters:
+
--
* `spec.bootImageSkewEnforcement.manual.mode`. Specifies the version you want to represent the current boot image, either `OCPVersion` or `RHCOSVersion`. You must include one of the following parameters:
* . Specifies the {op-system} or {product-title} version of the current boot image. 
** For `RHCOSVersion`, use `spec.bootImageSkewEnforcement.manual.rhcosVersion` to specify the {op-system} version that is being used as a boot image in the `[major].[minor].[datestamp(YYYYMMDD)]-[buildnumber]` or `[major].[minor].[timestamp(YYYYMMDDHHmm)]-[buildnumber]` format. This field must be between 14 and 21 characters long.
** For `OCPVersion`, use `spec.bootImageSkewEnforcement.manual.ocpVersion` to  specify the {product-title} version associated with the boot image that is being used in the `x.y.z` format. This field must be between 5 and 10 characters long.
--
