// Module included in the following assemblies:
//
// * machine-configuration/mco-update-boot-images.adoc
// * nodes/nodes/nodes-update-boot-images.adoc

:_mod-docs-content-type: REFERENCE
[id="mco-update-boot-skew-mgmt-about.adoc_{context}"]
= About boot image skew enforcement

Boot image skew enforcement allows an admin to configure how boot image version skew is enforced on the cluster.

During the upgrade from {product-title} version 4.20, you are required to specify a For clusters that do not support automatic boot image updates, cluster upgrades will be disabled until a skew enforcement mode has been specified.

When version skew is being enforced, cluster upgrades will be disabled until the version skew is deemed acceptable for the current release payload.

The `bootImageSkewEnforcement` paramater takes one of the following modes:

* `Automatic`. Boot image skew enforcement is active. This value is available only for :aws-short:, :gcp-short:, :azure-short:, and :vmw-short: clusters and is the default for these platforms. In `Automatic` mode, the Machine Config Operator (MCO) performs boot image updates and stores the {product-title} or {op-system} version associated with the last boot image update in the `automatic` field, as shown in the examples in this section. The MCO prevents upgrades when the specified boot image skew exceeds the skew limit described by the release image.
* `Manual`. The cluster admin is responsible to manually configure the boot image version based on the `ocpVersion` or `rhcosVersion` parameter. For the `Manual` mode, boot image skew enforcement is based on either a {product-title} or {op-system} version, as shown in the examples in this section. A cluster admin performs manual boot image updates and stores the {product-title} or {op-system} version associated with the last boot image update in the `manual` field. The MCO prevents upgrades when the specified boot image skew exceeds the skew limit described by the release image.
* `None`. Boot image management is disabled. When disabled, upon scaling up, new nodes might be provisioned with older boot images that could introduce compatibility issues. The MCO no longer monitors the boot image skew. This can affect the cluster's ability to scale.

:FeatureName: Boot image skew enforcement
include::snippets/technology-preview.adoc[]

. Example `MachineConfig` object with skew enforcement based on an {op-system} version
[source,yaml]
----
apiVersion: operator.openshift.io/v1
kind: MachineConfiguration
metadata:
  name: cluster
# ...
spec:
  bootImageSkewEnforcement:
    mode: Manual
    manual:
      mode: RHCOSVersion
      rhcosVersion: 9.0.20251023-0
# ...
----

. Example `MachineConfig` object with skew enforcement based on an {product-title} version
[source,yaml]
----
apiVersion: operator.openshift.io/v1
kind: MachineConfiguration
metadata:
  name: cluster
# ...
spec:
  bootImageSkewEnforcement:
    mode: Manual
    manual:
      mode: OCPVersion
      ocpVersion: 4.22.1
# ...
----

. Example `MachineConfig` object with skew enforcement disabled
[source,yaml]
----
apiVersion: operator.openshift.io/v1
kind: MachineConfiguration
metadata:
  name: cluster
# ...
spec:
  bootImageSkewEnforcement:
    mode: None
# ...
----
. Example `MachineConfig` object with automatic skew enforcement
[source,yaml]
----
apiVersion: operator.openshift.io/v1
kind: MachineConfiguration
metadata:
  name: cluster
status:
# ...
  bootImageSkewEnforcementStatus:
    automatic:
      ocpVersion: 4.22.0
    mode: Automatic
# ...
----
