// Module included in the following assemblies:
//
// * machine-configuration/mco-update-boot-skew-mgmt.adoc

:_mod-docs-content-type: CONCEPT
[id="mco-update-boot-skew-mgmt-about.adoc_{context}"]
= About boot image skew enforcement

[role="_abstract"]
Using boot image skew enforcement you can ensure that the boot images in a cluster are up-to-date with the {product-title} and {op-system} version being used in the cluster. Making sure that your boot images are current can help you avoid the problems associated with running older images.

When boot image skew enforcement is active in a cluster, the Machine Config Operator (MCO) examines the boot image version reported in the `MachineConfiguration` object to determine if that boot image is appropriate for the cluster. If the boot image version is too old, the Operator reports that _boot image version skew_ is detected and blocks cluster updates until you manually update the boot image or set boot image skew enforcement to the `None` mode, as described in this section. 

The limit for boot image version skew is set within the MCO and cannot be modified.

For information on manually configuring the boot image in your cluster, see "Manually updating the boot image."

:FeatureName: Boot image skew enforcement
include::snippets/technology-preview.adoc[]

Boot image skew enforcement operates in one of the following modes:

Automatic:: 
In automatic mode, when the cluster is updated from one {product-title} version to the next, with boot image management also enabled, the MCO automatically updates the boot image version in the `MachineConfiguration` object and tests the boot image version for skew. Boot image management must be enabled in the node to use the automatic mode. 
+
[NOTE]
====
In {product-title} 4.22, the automatic mode is available only for {aws-short}, {gcp-short}, {azure-short}, and {vmw-short} clusters and is the default for these platforms. 
====
+
For information on boot image management, see "Boot image management".
+
.Example `MachineConfiguration` object with automatic skew enforcement
[source,yaml]
----
apiVersion: operator.openshift.io/v1
kind: MachineConfiguration
metadata:
  name: cluster
status:
# ...
  bootImageSkewEnforcement:
    mode: Automatic
    automatic:
      ocpVersion: 4.22.0
# ...
  bootImageSkewEnforcementStatus:
    automatic:
      ocpVersion: 4.22.0
    mode: Automatic
----
+
The MCO examines the boot image reported in the `ocpVersion` parameter to determine if the cluster is violating the boot image version skew limits.

Manual:: In manual mode, when the boot image version is updated, a cluster administrator is responsible to manually update the `MachneConfiguration` object with the {op-system} version of the boot image or the {product-title} associated with the boot image. The MCO then tests the boot image version for skew.
+
For information on boot image management, see "Boot image management".
+
.Example `MachineConfiguration` object with skew enforcement based on an {op-system} version
[source,yaml]
----
apiVersion: operator.openshift.io/v1
kind: MachineConfiguration
metadata:
  name: cluster
# ...
spec:
  bootImageSkewEnforcement:
    mode: Manual
    manual:
      mode: RHCOSVersion
      rhcosVersion: 9.2.20251023-0
# ...
status:
  bootImageSkewEnforcementStatus:
    manual:
      mode: RHCOSVersion
      rhcosVersion: 9.2.20251023-0
    mode: Manual
----
+
.Example `MachineConfiguration` object with skew enforcement based on an {product-title} version
[source,yaml]
----
apiVersion: operator.openshift.io/v1
kind: MachineConfiguration
metadata:
  name: cluster
# ...
spec:
  bootImageSkewEnforcement:
    mode: Manual
    manual:
      mode: OCPVersion
      ocpVersion: 4.22.0
# ...
status:
  bootImageSkewEnforcementStatus:
    manual:
      mode: OCPVersion
      ocpVersion: 4.22.0
    mode: Manual
----
+
The MCO examines the boot image reported in the `rhcosVersion` or `ocpVersion` parameters to determine if the cluster is violating the boot image version skew limits.

None:: 
In None mode, boot image management is disabled. When disabled, the MCO does not monitor for boot image skew and does not report if new nodes are provisioned with older boot images that could introduce compatibility issues. This can affect the cluster's ability to scale. 
+
.Example `MachineConfiguration` object with skew enforcement disabled
[source,yaml]
----
apiVersion: operator.openshift.io/v1
kind: MachineConfiguration
metadata:
  name: cluster
# ...
spec:
  bootImageSkewEnforcement:
    mode: None
# ...
status:
  bootImageSkewEnforcementStatus:
    mode: None
----

