// Module included in the following assemblies:
//
// * nodes/nodes-containers-port-forwarding.adoc

:_mod-docs-content-type: PROCEDURE
[id="mco-update-boot-images-nutanix_{context}"]
= Updating the boot image on a Nutanix cluster

[role="_abstract"]
For a Nutanix cluster, you can manually update the boot image for your cluster by configuring your machine sets to use the latest {product-title} image as the boot image. By updating the boot image, you can ensure that the {op-system-first} version on new nodes is up-to-date.

[NOTE]
====
The standard boot image management feature is not supported for Nutanix clusters.
====

The following procedure, which includes steps that create environment variables to facilitate running the required commands, shows how to obtain Nutanix authentication credentials, download a boot image, upload that image to the Nutanix Prism Central, and modify your worker machine sets to use the new boot image.

This procedure requires Nutanix authentication credentials, which you need to access Prism Central. If you need to recover your credentials, you can get them from an {product-title} secret, the name of which you can find in the default compute machine set. You can decrypt this secret and export the credentials to create the `clouds.yaml` file, as described in the following procedure.

.Prerequisites

* You have completed the general boot image prerequisites as described in the Prerequisites section of link:https://access.redhat.com/articles/7053165#prerequisites-2[{product-title} Boot Image Updates].

* You have downloaded the latest version of the {product-title} installation program from the {cluster-manager-url}. For more information, see "Obtaining the installation program."

* You have the {oc-first} installed.

.Procedure

. If you need to recover your Nutanix authentication credentials, perform the following steps: 

.. Obtain the name of the secret that contains your credentials by running the following command:
+
[source,terminal]
----
$ oc get machineset -n openshift-machine-api -o yaml | grep credentialsSecret -A 1
----
+
. Example output
[source,terminal]
----
    credentialsSecret:
      name: nutanix-credentials
----

.. Decrypt the secret and add the contents to the `clouds.yaml` file by running the following command:
+
[source,terminal]
----
oc get secret <secret-name> -n openshift-machine-api -o jsonpath='{.data.credentials}' | base64 -d
----
+
Replace `<secret-name>` with the name of the secret, which you obtained in the previous step.
+
. Example output
[source,terminal]
----
[{"type":"basic_auth","data":{"prismCentral":{"username":"","password":""},"prismElements":null}}]
----

. Set environment variables for the Nutanix username and password by running the following commands:
+
[source,terminal]
----
$ export USER="<username>"
----
+
[source,terminal]
----
$ export PASS="<password>"
----

. If you need to recover your IP address for Prism Central, run the following command:
+
[source,terminal]
----
$ oc get configmap cloud-provider-config -n openshift-config -o jsonpath='{.data.config}' | grep prismCentral -A 8
----
+
. Example output
[source,terminal]
----
    "prismCentral": {
        "address": "",
        "port": 9440,
        "credentialRef": {
            "kind": "Secret",
            "name": "nutanix-credentials",
            "namespace": "openshift-cloud-controller-manager"
        }
    },
----
where:

`prismCentral.address`:: Specifies the Prism Central IP.

. Set an environment variables for the Prism Central IP value by running the following command:
+
[source,terminal]
----
$ export PC_IP="<prism-central-ip-value>"
----

. Obtain the boot image and upload the image to Prism Central:

.. Obtain the URL of the {op-system} image you want to use as the boot image and set the location in an environment variable by running the following command
+
[source,terminal]
----
$ export RHCOS_URL=$(openshift-install coreos print-stream-json | jq -r '.architectures.x86_64.artifacts.nutanix.formats.qcow2.disk.location')
----

.. Set an environment variable to create a descriptive name for your boot image in Prism Central by running the following command:
+
[source,terminal]
----
$ export IMAGE_NAME="<descriptive_image_name>"
----
+
Setting a descriptive name for your boot image, such as using the {op-system-first} version number in the image name, makes it easier to track which version is currently deployed if you update the cluster in the future.
+
.Example command
[source,terminal]
----
$ export IMAGE_NAME="rhcos 9.6 boot image"
----

.. Upload the image to Prism Central by running the following command:
+
[source,terminal]
----
$ curl -k -u "$USER:$PASS" \
  -X POST "https://$PC_IP:9440/api/nutanix/v3/images" \
  -H "Content-Type: application/json" \
  -d '{
    "spec": {
      "name": "'"$IMAGE_NAME"'",
      "resources": {
        "image_type": "DISK_IMAGE",
        "source_uri": "'"$RHCOS_URL"'"
      }
    },
    "metadata": {
      "kind": "image"
    }
  }'
----
+
`USER`,`PASS`, `IMAGE_NAME`, and `RHCOS_URL` are environment variables you created in previous steps.

.. Optional: Verify that the image uploaded by running the following command:
+
[source,terminal]
----
$ curl -k -u "$USER:$PASS" \
  -X POST "https://$PC_IP:9440/api/nutanix/v3/images/list" \
  -H "Content-Type: application/json" \
  -d '{
    "kind": "image",
    "filter": "name=='"$IMAGE_NAME"'"
  }' | jq '.entities[] | {name: .status.name, state: .status.state}'
{
  "name": "<image-name>",
  "state": "COMPLETE"
}
----

. Update each of your compute machine sets to include the new boot image:

.. Obtain the name of your machine sets for use in the following step by running the following command:
+
[source,terminal]
----
$ oc get machineset -n openshift-machine-api
----
+
.Example output
[source,terminal]
----
NAME                                 DESIRED   CURRENT   READY   AVAILABLE   AGE
rhhdrbk-b5564-4pcm9-worker-0         3         3         3       3           123m
ci-ln-xj96skb-72292-48nm5-worker-d   1         1         1       1           27m
----

.. Edit a machine set to update the `image` field in the `providerSpec` stanza to point add your boot image by running the following command:
+
[source,terminal]
----
$ oc patch machineset <machineset-name> -n openshift-machine-api --type merge -p '{"spec":{"template":{"spec":{"providerSpec":{"value":{"image":{"type":"name","name":"'${IMAGE_NAME}'"}}}}}}}'  
----
+
Replace `<machineset_name>` with the name of your machine set.

.Verification

. Scale up a machine set to check that the new node is using the your boot image:

.. Increase the machine set replicas by one to trigger a new machine by running the following command:
+
[source,terminal]
----
$ oc scale --replicas=<count> machineset <machineset_name> -n openshift-machine-api
----
where:

`<count>`:: Specifies the total number of replicas, including any existing replicas, that you want for this machine set.
`<machineset_name>`:: Specifies the name of the machine set to scale.

.. Optional: View the status of the machine set as it is created by running the following command:
+
[source,terminal]
----
$ oc get machines.machine.openshift.io -n openshift-machine-api -w
----
+
It can take several minutes for the machine set to achieve the `Running` state.

.. Verify that the new node has been created and is in the `Ready` state by running the following command.
+
[source,terminal]
----
$ oc get nodes
----

.. Verify that the new node is using your boot image by running the following command:
+
[source,terminal]
----
$ oc debug node/<new_node> -- chroot /ho	st cat /sysroot/.coreos-aleph-version.json
----
+
Replace `<new_node>` with the name of your new node.
+
.Example output
[source,terminal]
----
{
# ...
    "ref": "docker://ostree-image-signed:oci-archive:/rhcos-9.6.20251212-1-ostree.x86_64.ociarchive",
    "version": "9.6.20251212-1"
}
----
where:

`<version>`:: Specifies the boot image version.

.. Verify that the boot image is the same version as the image you uploaded in a previous step by running the following command:
+
[source,terminal]
----
$ echo ${RHCOS_URL}
----
+
.Example output
[source,terminal]
----
https://rhcos.mirror.openshift.com/art/storage/prod/streams/rhel-9.6/builds/9.6.20251212-1/x86_64/rhcos-9.6.20251212-1-nutanix.x86_64.qcow2
----
