// Module included in the following assemblies:
//
// * nodes/nodes-containers-port-forwarding.adoc

:_mod-docs-content-type: PROCEDURE
[id="mco-update-boot-images-openstack_{context}"]
= Updating the boot image on an OpenStack cluster

[role="_abstract"]
For a {rh-openstack-first} cluster, you can manually update the boot image for your cluster by configuring your machine sets to use the latest {product-title} image as the boot image. By updating the boot image, you can ensure that the {op-system-first} version on new nodes is up-to-date.

[NOTE]
====
The standard boot image management feature is not supported for {rh-openstack} clusters.
====

The following procedure, which includes steps that create environment variables to facilitate running the required commands, shows how to obtain {rh-openstack} authentication credentials, download a boot image, upload that image to the {rh-openstack} image service (Glance), and modify your worker machine sets to use the new boot image.

This procedure requires the `clouds.yaml` file, which is needed to connect to your {rh-openstack} cloud. If you need to re-create this file, you can get the {rh-openstack} credentials from an {product-title} secret, the name of which you can find in the default compute machine set. You can decrypt this secret and export the credentials to create the `clouds.yaml` file, as described in the following procedure.

[NOTE]
====
Updating control plane machine sets is not supported in {rh-openstack}.
====

.Prerequisites

* You have downloaded the latest version of the OpenShift installation program from the {cluster-manager-url}. For more information, see "Obtaining the installation program."

* You have the {oc-first} installed.

* You have installed an link:https://docs.openstack.org/python-openstackclient/latest/[{rh-openstack}Client ({op-system} documentation)].

.Procedure

. If you need to recreate the `clouds.yaml` file, perform the following steps: 

.. Obtain the name of the secret that contains your credentials by running the following command:
+
[source,terminal]
----
$ oc get machineset -n openshift-machine-api -o yaml | grep cloudsSecret -A 1
----
+
.Example output
[source,terminal]
----
cloudsSecret:
  name: openstack-cloud-credentials
----

.. Decrypt the secret and add the contents to the `clouds.yaml` file by running the following command:
+
[source,terminal]
----
$ oc get secret <secret-name> -n openshift-machine-api -o jsonpath='{.data.clouds\.yaml}' | base64 -d > /tmp/clouds.yaml
----
+
Replace `<secret-name>` with the name of the secret, which you obtained in the previous step.

.. Optional: Verify the contents of the `clouds.yaml` file by running the following command:
+
[source,terminal]
----
$ cat /tmp/clouds.yaml
----
+
.Example output
[source,terminal]
----
clouds:
  openstack:
    auth:
      auth_url: https://your-openstack-url:13000
      username: "your-username"
      password: "your-password"
      project_name: "your-project"
      user_domain_name: "Default"
      project_domain_name: "Default"
----

.. Set an environment variable for the location of the `clouds.yaml` file by running the following command:
+
[source,terminal]
----
$ export OS_CLIENT_CONFIG_FILE=/tmp/clouds.yaml
----

. Obtain the name of your {rh-openstack} cloud from the default compute machine set and set the name in an environment variable by running the following command:
+
[source,terminal]
----
$ export CLOUD_NAME=$(oc get machineset -n openshift-machine-api -o jsonpath='{.items[0].spec.template.spec.providerSpec.value.cloudName}')
----

. Obtain the URL of the {op-system} image you want to be use as the boot image and set the location in an environment variable by running the following command, based on cluster architecture, by running one of the following commands.
+
* Linux (x86_64, amd64):
+
[source,terminal]
----
$ export RHCOS_URL=$(openshift-install coreos print-stream-json | jq -r \
'.architectures.x86_64.artifacts.openstack.formats."qcow2.gz".disk.location')
----
+
* Linux on {ibm-z-name} and {ibm-linuxone-name} (s390x):
+
[source,terminal]
----
$ export RHCOS_URL=$(openshift-install coreos print-stream-json | jq -r \
'.architectures.s390x.artifacts.openstack.formats."qcow2.gz".disk.location')
----
+
* Linux on ARM (aarch64, arm64)
+
[source,terminal]
----
$ export RHCOS_URL=$(openshift-install coreos print-stream-json | jq -r \
'.architectures.aarch64.artifacts.openstack.formats."qcow2.gz".disk.location')
----

. Obtain the boot image and upload the image to the {rh-openstack} image service (Glance):

.. Download the image by using the following command, which contains the URL environment variable you created in a previous step: 
+
[source,terminal]
----
$ curl -L -o /tmp/rhcos-new.qcow2.gz "${RHCOS_URL}"
----

.. Decompress the downloaded image by using the following command:
+
[source,terminal]
----
$ gunzip /tmp/rhcos-new.qcow2.gz
----

.. Set an environment variable to create a descriptive name for your boot image in Glance by running the following command:
+
[source,terminal]
----
$ export IMAGE_NAME="<descriptive_image_name>"
----
+
Setting a descriptive name for your boot image, such as using the {op-system-first} version number in the image name, makes it easier to track which version is currently deployed if you update the cluster in the future.
+
.Example command
[source,terminal]
----
$ export IMAGE_NAME="rhcos 9.6 boot image"
----

.. Upload the image to Glance by using the following command:
+
[source,terminal]
----
$ openstack --os-cloud "${CLOUD_NAME}" image create "${IMAGE_NAME}" \
  --disk-format qcow2 \
  --container-format bare \
  --file /tmp/rhcos-new.qcow2 \
  --property os_type=linux \
  --property os_distro=rhcos
----
+
`{CLOUD_NAME}` and `{IMAGE_NAME}` are environment variables you created in previous steps.
+
It might take several minutes for the image to upload. When the upload is complete, details on the image displays, similar to the following example:
+
[source,terminal]
----
+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Field            | Value                                                                                                                                                                               |
+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| checksum         | 469fa549f706617ff15b41bd2a919679                                                                                                                                                    |
# ...                                                                                                                                                         |
| disk_format      | qcow2                                                                                                                                                                               |
# ...
| name             | rhcos 9.6 boot image            
----

.. Optional: Verify that the image has uploaded and is in active state by running the following command:
+
[source,terminal]
----
$ openstack --os-cloud "${CLOUD_NAME}" image show "${IMAGE_NAME}" -f json | jq '{name: .name, status: .status}'
----
+
.Example output
[source,terminal]
----
{
  "name": "rhcos 9.6 boot image",
  "status": "active"
}
----

. Obtain the name of your machine sets for use in the following step.
+
[source,terminal]
----
$ oc get machineset -n openshift-machine-api
----
+
.Example output
[source,terminal]
----
NAME                                 DESIRED   CURRENT   READY   AVAILABLE   AGE
rhhdrbk-b5564-4pcm9-worker-0         3         3         3       3           123m
ci-ln-xj96skb-72292-48nm5-worker-d   1         1         1       1           27m
----

. Edit a machine set to update the `image` field in the `providerSpec` stanza to point add your boot image by running the following command.
+
[source,terminal]
----
$ oc patch machineset <machineset_name> -n openshift-machine-api --type merge -p \
'{"spec":{"template":{"spec":{"providerSpec":{"value":{"image":"'${IMAGE_NAME}'"}}}}}}'
----
+
Replace `<machineset_name>` with the name of your machine set.

.Verification

. Scale up a machine set to check that the new node is using the your boot image:

.. Increase the machine set replicas by one to trigger a new machine by running the following command:
+
[source,terminal]
----
$ oc scale --replicas=<count> machineset <machineset_name> -n openshift-machine-api
----
where:

`<count>`:: Specifies the total number of replicas, including any existing replicas, that you want for this machine set.
`<machineset_name>`:: Specifies the name of the machine set to scale.

.. Optional: View the status of the machine set as it is created by running the following command:
+
[source,terminal]
----
$ oc get machines.machine.openshift.io -n openshift-machine-api -w
----
+
It can take several minutes for the machine set to achieve the `Running` state.

.. Verify that the new node has been created and is in the `Ready` state by running the following command.
+
[source,terminal]
----
$ oc get nodes
----

.. Verify that the new node is using your boot image by running the following command:
+
[source,terminal]
----
$ oc debug node/<new_node> -- chroot /ho	st cat /sysroot/.coreos-aleph-version.json
----
+
Replace `<new_node>` with the name of your new node.
+
.Example output
[source,terminal]
----
{
# ...
    "ref": "docker://ostree-image-signed:oci-archive:/rhcos-9.6.20251023-0-ostree.x86_64.ociarchive",
    "version": "9.6.20251023-0"
}
----
where:

`<version>`:: Specifies the boot image version.
