// Module included in the following assemblies:
//
// * machine-configuration/mco-update-boot-images.adoc
// * nodes/nodes/nodes-update-boot-images.adoc

:_mod-docs-content-type: CONCEPT
[id="mco-update-boot-skew-mgmt-about.adoc_{context}"]
= About boot image skew enforcement

Boot image skew enforcement allows you to ensure that the boot images in a cluster are up-to-date with the {product-title} and {op-system} version being used in the cluster. Using an older boot image could cause compatibility issues within your cluster.

When boot image skew enforcement is active in a cluster, the Machine Config Operator (MCO) examines the boot image version reported in the `MachineConfiguration` object to determine if the boot image being used is appropriate for the cluster. If the boot image version is too old, the Operator reports that boot image version skew is detected and blocks cluster updates until you manually update the boot image or disable boot image skew enforcement. For information on manually configuring the boot image in your cluster, see "Manually updating the boot image."

The limit for boot image version skew is set within the MCO and cannot be modified.

:FeatureName: Boot image skew enforcement
include::snippets/technology-preview.adoc[]

Boot image skew enforcement operates in one of the following modes:

Automatic:: 
In automatic mode, the MCO automatically updates the boot image version on the nodes in the cluster when the cluster is updated from one {product-title} version to the next. 
+
[NOTE]
====
In {product-title} 4.22, the automatic mode is available only for {aws-short}, {gcp-short}, {azure-short}, and {vmw-short} clusters and is the default for these platforms. 
====
+
The Operator tracks the {op-system} or {product-title} version of the current boot image in the `MachineConfigutation` object, which is based on current cluster version.
+
.Example `MachineConfig` object with automatic skew enforcement
[source,yaml]
----
apiVersion: operator.openshift.io/v1
kind: MachineConfiguration
metadata:
  name: cluster
status:
# ...
  bootImageSkewEnforcement:
    mode: Automatic
    automatic:
      ocpVersion: 4.22.0
# ...
  bootImageSkewEnforcementStatus:
    automatic:
      ocpVersion: 4.22.0
    mode: Automatic
----
+
The MCO examines the boot image reported in the `ocpVersion` parameter to determine if the cluster is violating the boot image version skew limits.

Manual:: In manual mode, a cluster administrator is responsible to manually update the boot image on the nodes in the cluster and to track the {op-system} version of the boot image or the {product-title} associated with the boot image. 
+
.Example `MachineConfig` object with skew enforcement based on an {op-system} version
[source,yaml]
----
apiVersion: operator.openshift.io/v1
kind: MachineConfiguration
metadata:
  name: cluster
# ...
spec:
  bootImageSkewEnforcement:
    mode: Manual
    manual:
      mode: RHCOSVersion
      rhcosVersion: 9.2.20251023-0
# ...
status:
  bootImageSkewEnforcementStatus:
    manual:
      mode: RHCOSVersion
      rhcosVersion: 9.2.20251023-0
    mode: Manual
----
+
.Example `MachineConfig` object with skew enforcement based on an {product-title} version
[source,yaml]
----
apiVersion: operator.openshift.io/v1
kind: MachineConfiguration
metadata:
  name: cluster
# ...
spec:
  bootImageSkewEnforcement:
    mode: Manual
    manual:
      mode: OCPVersion
      ocpVersion: 4.22.1
# ...
status:
  bootImageSkewEnforcementStatus:
    manual:
      mode: OCPVersion
      ocpVersion: 4.22.0
    mode: Manual
----
+
The MCO examines the boot image reported in the `rhcosVersion` or `ocpVersion` parameters to determine if the cluster is violating the boot image version skew limits.

None:: 
Boot image management is disabled. When disabled, the MCO does not monitor for boot image skew. Upon scaling up new nodes, those nodes might be provisioned with older boot images that could introduce compatibility issues. This can affect the cluster's ability to scale. 
+
.Example `MachineConfig` object with skew enforcement disabled
[source,yaml]
----
apiVersion: operator.openshift.io/v1
kind: MachineConfiguration
metadata:
  name: cluster
# ...
spec:
  bootImageSkewEnforcement:
    mode: None
# ...
status:
  bootImageSkewEnforcementStatus:
    mode: None
----

