// Module included in the following assemblies:
//
// * machine-configuration/mco-update-boot-images.adoc
// * nodes/nodes-nodes-managing.adoc

:_mod-docs-content-type: PROCEDURE
[id="mco-update-boot-images-opt-out_{context}"]
= Opting out of updated boot images

To opt out of the updated boot image feature, edit the `MachineConfiguration` object to remove the `managedBootImages` stanza.

If you disable this feature after some nodes have been created with the new boot image version, any existing nodes retain their current boot image. Turning off this feature does not rollback the nodes or machine sets to the originally-installed boot image. The machine sets retain the boot image version that was present when the feature was enabled and is not updated again when the cluster is upgraded to a new {product-title} version in the future.

.Procedure

. Edit the `MachineConfiguration` object to opt out some or all of your nodes:
+
[source,terminal]
----
$ oc edit MachineConfiguration cluster
----

* Optional: Opt out of the boot image update feature for all machine sets:
+
[source,yaml]
----
apiVersion: operator.openshift.io/v1
kind: MachineConfiguration
metadata:
  name: cluster
  namespace: openshift-machine-config-operator
spec:
# ...
  managedBootImages: <1>
    machineManagers:
    - apiGroup: machine.openshift.io <2>
      resource: machinesets <3>
      selection:
        mode: None <4>
----
<1> Configures the boot image update feature.
<2> Specifies an API group. This must be `machine.openshift.io`.
<3> Specifies the resource within the specified API group to apply the change to. This must be `machinesets`.
<4> Specifies that nodes in all machine sets in the cluster are opted in.

* Optional: Opt out of the boot image update feature for specific machine sets:
+
[source,yaml]
----
apiVersion: operator.openshift.io/v1
kind: MachineConfiguration
metadata:
  name: cluster
  namespace: openshift-machine-config-operator
spec:
# ...
  managedBootImages: <1>
    machineManagers:
    - apiGroup: machine.openshift.io <2>
      resource: machinesets <3>
      selection:
        mode: Partial <4>
        partial: <5>
          machineResourceSelector:
            matchLabels:
              region: "east"
----
<1> Configures the boot image update feature.
<2> Specifies an API group. This must be `machine.openshift.io`.
<3> Specifies the resource within the specified API group to apply the change to. This must be `machinesets`.
<4> Specifies that a set of nodes in the cluster is opted out.
<5> Specifies that any machine set with this label is to be updated.

.Verification

include::snippets/mco-update-boot-images-verification.adoc[]

* Get the boot image version by running the following command:
+
[source,terminal]
----
$ oc get machinesets <machineset_name> -n openshift-machine-api -o yaml
----
+
.Example machine set with the boot image reference
+
[source,yaml]
----
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: ci-ln-77hmkpt-72292-d4pxp
    update-boot-image: "true"
  name: ci-ln-77hmkpt-72292-d4pxp-worker-a
  namespace: openshift-machine-api
spec:
# ...
  template:
# ...
    spec:
# ...
      providerSpec:
# ...
        value:
          disks:
          - autoDelete: true
            boot: true
            image: projects/rhcos-cloud/global/images/rhcos-416-92-202402201450-0-gcp-x86-64 <1>
# ...
----
<1> This boot image is the same as the current {product-title} version.

