// Module included in the following assemblies:
//
// * nodes/nodes-sigstore-using.adoc

:_mod-docs-content-type: CONCEPT
[id="nodes-sigstore-configure_{context}"]
= Configuring Sigstore support

You can use the `ClusterImagePolicy` and `ImagePolicy` custom resource (CR) objects to enable and configure Sigstore support for the entire cluster or specific namespaces. These objects specify the images and repositories to be verified by using Sigstore tooling.

* Cluster image policy. A cluster image policy object enables a cluster administrator to configure a Sigstore signature verification policy for the entire cluster. When enabled, the Machine Config Operator (MCO) watches the `ClusterImagePolicy` object and updates the `/etc/crio/<namespace>.json` and `/etc/containers/registries.d/sigstore-registries.yaml` files on all nodes in the cluster.

[IMPORTANT]
====
The default `openshift` cluster image policy provides Sigstore support for the required {product-title} images. You should not remove or modify this cluster image policy object.
====

* Image policy. An image policy enables a cluster administrator or application developer to configure a Sigstore signature verification policy for a specific namespace. The MCO watches an `ImagePolicy` instance in different namespaces and creates or updates the `/etc/crio/<namespace>.json` and `/etc/containers/registries.d/sigstore-registries.yaml` files on all nodes in the cluster.
+
If the image or repository in an image policy is nested under one of the images or repositories in a cluster image policy, only the policy from cluster image policy is applied. For example, if an image policy specifies `example.com/global/image`, and the cluster image policy specifies `example.com/global`, the namespace uses the policy from the cluster image policy. The image policy object is created and shows an error similiar to the following message:

.Example image policy with a conflicting image identity
[source,yaml]
----
API Version:  config.openshift.io/v1alpha1
Kind:         ImagePolicy
Name:         p0
Namespace:    mynamespace
# ...
Status:
  Conditions:
    Message: has conflicting scope(s) ["example.com/global/image"] that equal to or nest inside existing clusterimagepolicy, only policy from clusterimagepolicy scope(s) will be applied
    Reason: ConflictScopes
# ...
----

[id="nodes-sigstore-configure-parameters_{context}"]
== About image policy parameters

The following parameters apply to cluster and image policies. For information on using these parameters, see "Creating a cluster image policy CR" and "Creating an image policy CR".

// Based on https://github.com/openshift/api/blob/master/config/v1alpha1/zz_generated.crd-manifests/0000_10_config-operator_01_imagepolicies-TechPreviewNoUpgrade.crd.yaml

`scopes`:: Defines a list of  image identities assigned to a policy. You must list at least one image identity. An image identity can refer to any of the following identities:
+
--
* An individual image, by using a tag or digest, such as `example.com/namespace/image:latest`
* A repository by omitting the tag or digest, such as `example.com`
* A repository namespace, such as `example.com/namespace/`
* A registry host, by specifying only the host name and port number or a wildcard expression starting with `\*.`, such as `*.example.com`
--
+
If multiple image identities match a single image, the policy for only the most specific image identity applies.
+
In a cluster image policy, make sure that the policy allows deployment of the {product-title} images in the `quay.io/openshift-release-dev/ocp-release` and `quay.io/openshift-release-dev/ocp-v4.0-art-dev` repositories. Images in these repositories are required for cluster operation.

`policy`:: Contains configuration to allow images from the sources listed in `scopes` to be verified, and defines how images not matching the verification policy will be treated. You must configure a `rootOfTrust` and optionally, a `signedIdentity`.
* `rootOfTrust`: Specifies the root of trust for the policy. Configure for either a public key, optionally including a Rekor verification, or a Fulcio certification.
** `publicKey`:  Indicates that the policy relies on a Sigstore public key. You must specify a base64-encoded PEM format public key. You can optionally include Rekor verification.
** `FulcioCAWithReko`: Indicates that the policy is based on the Fulcio certification. You must specify the following parameters:
*** A base64-encoded PEM format Fulcio CA
*** An OpenID Connect (OIDC) issuer
*** The email of the Fulcio authentication configuration
*** The Rekor verification
* `signedIdentity`: Optionally specifies the approach used in the verification process to verify the image in the signature and the actual image itself. You must specify one of the following parameters for the match policy:
** `MatchRepoDigestOrExact`. If the image uses a digest reference, the image referenced in the signature must be in the same repository as the image itself. If the image identity carries a tag, the image referenced in the signature must match exactly. This is the default.
** `MatchRepository`. The image referenced in the signature must be in the same repository as the image itself. This is useful to pull an image that contains the `latest` tag if the image is signed with a tag specifying an exact image version.
** `ExactRepository`. The image referenced in the signature must be in the same repository that is specified by the `repository` parameter. The `exactRepository` parameter must be specified.
** `RemapIdentity`. If the image prefix matches a specified `prefix`, that prefix is replaced by the specified `signedPrefix`. The `prefix` and `signedPrefix` can be either `host[:port]` values that matching the exact `host[:port], string`, repository namespaces, or repositories. The `prefix` and `signedPrefix` must not contain tags or digests. For example, to specify a single repository, use `example.com/library/busybox` and not `busybox`. To specify the parent namespace of `example.com/library/busybox`, you can use `example.com/library`. The maximum length is 512 characters. You must specify the following parameters:
*** `prefix`: Specifies the image prefix to be matched. If the image prefix matches the specified `prefix`, that prefix is replaced by the specified `signedPrefix`. This useful when verifying signatures for a mirror of some other repository namespace that preserves the vendor’s repository structure. If the image identity does not match, the `prefix` is unchanged and no remapping takes place.
*** `signedPrefix`: Specifies the image prefix to be remapped, if needed.

[id="nodes-sigstore-configure-parameters-modify_{context}"]
== About modifying or removing image policies

You can modify or remove a cluster image policy or image policy using the same commands as any other custom resource (CR) object.

You can modify an existing policy by editing the policy YAML and running an `oc apply` command on the file or directly editing the `ClusterImagePolicy` and `ImagePolicy` object. Both methods apply the changes in the same manner.

You can create multiple policies for a cluster or namespace. This allows you to create different policies for different images or repositories.

You can remove a policy by deleting the the `ClusterImagePolicy` and `ImagePolicy` object.
