// Module included in the following assemblies:
//
// * nodes/nodes-nodes-rebooting.adoc

[id="nodes-nodes-rebooting-infrastructure_{context}"]
= Understanding how to reboot nodes running critical infrastructure

When rebooting nodes that host critical {product-title} infrastructure components, such as the router pods, the registry pods, and monitoring pods, ensure that there are at least three nodes available to run these components.

The scenario below demonstrates the service interruptions that can occur with applications running on {product-title} when only two nodes are available:

- Node A is marked unschedulable and all pods are evacuated.
- The registry pod running on that node is now redeployed on node B. This means
node B is now running both registry pods.
- Node B is now marked unschedulable and is evacuated.
- The service exposing the two pod endpoints on node B, for a brief period of
   time, loses all endpoints until they are redeployed to node A.

The same process when using three nodes for infrastructure does not result in a service disruption. However, due to pod scheduling, the last node that is evacuated and brought back in to rotation does not run a registry. One of the other nodes runs two registries. To schedule the third registry to the last node, use pod anti-affinity to prevent the scheduler from locating two registry pods on the same node.
