// Module included in the following assemblies:
//
// * nodes/nodes-nodes-rebooting.adoc

[id="nodes-nodes-rebooting-infrastructure_{context}"]
= Understanding how to reboot master nodes running critical infrastructure

When rebooting the master nodes, which host critical {product-title} infrastructure components, ensure that there are at least three nodes available to run these components. 

The scenario below demonstrates a common mistake that can lead
to service interruptions for the applications running on {product-title} when
only two nodes are available.

- Node A is marked unschedulable and all pods are evacuated.
- The registry pod running on that node is now redeployed on node B. This means
node B is now running both registry pods.
- Node B is now marked unschedulable and is evacuated.
- The service exposing the two pod endpoints on node B, for a brief period of
   time, loses all endpoints until they are redeployed to node A.

The same process using three master nodes for infrastructure does not result in a service
disruption. However, due to pod scheduling, the last node that is evacuated and
brought back in to rotation is left running zero registries. The other two nodes
will run two and one registries respectively. The best solution is to rely on
pod anti-affinity.
