// Module included in the following assemblies:
//
// * operators/user/olm-installing-operators-in-namespace.adoc
// * operators/admin/olm-adding-operators-to-cluster.adoc
// * post_installation_configuration/preparing-for-users.adoc
//
// Module watched for changes by Ecosystem Catalog team:
// https://projects.engineering.redhat.com/projects/RHEC/summary


[id="olm-installing-operators-from-operatorhub-configure_{context}"]
= Configuring {product-title} to use Red Hat Operators

You muast have downloaded the link:https://cloud.redhat.com/openshift/install/pull-secret[pull secret from the Red Hat OpenShift Cluster Manager site] as shown in the installation procedure to install Red Hat Operators.

If you have the pull secret, edit the  OperatorHub custom resource (CR) to add the `redhat-operators` catalog.

. Edit the OperatorHub CR using the web console or CLI:

.. Using the CLI:

... Edit the OperatorHub CR object:
+
[source,terminal]
----
$ oc edit OperatorHub cluster
----

... Add `redhat-operators` to the list of sources and set to `disabled: false`:
+
.Example OperatorHub CR
[source,yaml]
----
apiVersion: config.openshift.io/v1
kind: OperatorHub
metadata:
  name: cluster
spec:
  disableAllDefaultSources: true
  sources:
  - disabled: false <1>
    name: redhat-operators
  - disabled: false
    name: community-operators
----
<1> Add the `redhat-operators` catalog as `disabled: false`. 

.. Using the web console:

... Switch to the *Administration* -> *Custom Resource Definitions* page.

... On the *Custom Resource Definitions* page, click *OperatorHub*.

... On the *Custom Resource Definition Overview* page, click *Instances*.

... On the *Instances* tab, click *cluster*.

... On the *Instances* tab, click *YAML*.

... In the YAML field, add `redhat-operators` to the list of sources and set to `disabled: false`:
+
.Example OperatorHub CR
[source,yaml]
----
apiVersion: config.openshift.io/v1
kind: OperatorHub
metadata:
  name: cluster
spec:
  disableAllDefaultSources: true
  sources:
  - disabled: false <1>
    name: redhat-operators
  - disabled: false
    name: community-operators
----
<1> Add the `redhat-operators` catalog as `disabled: false`. 

... Click *Save*.

. Log out of the web console, and then log back in.

