// Module included in the following assemblies:
//
// * support/troubleshooting/troubleshooting-operator-issues.adoc

[id="troubleshooting-disabling-autoreboot-mco-cli_{context}"]
= Disabling Machine Config Operator from automatically rebooting by using the CLI

To avoid unwanted disruptions from changes made by the Machine Config Operator (MCO), you can use the CLI to modify the machine config pool (MCP) to prevent automatic rebooting after the Operator makes changes to the machine config. 

[NOTE]
====
Pausing a machine config pool stops all updates to your {op-system} nodes, including updates to the operating system, security, certificate, and any other updates related to the machine config. Pausing should be done for short periods of time only.
====

.Prerequisites

* You have access to the cluster as a user with the `cluster-admin` role.
* You have installed the OpenShift CLI (`oc`).
* You have root access in {product-title}.

.Procedure
. To pause the MCO from rebooting {op-system} nodes:

* As root, update the `spec.paused` field to `true` in the `MachineConfigPool` custom resource.
+
.Control plane (master) nodes
[source,terminal]
----
# oc patch --type=merge --patch='{"spec":{"paused":true}}' machineconfigpool/master
----
+
.Worker nodes
[source,terminal]
----
# oc patch --type=merge --patch='{"spec":{"paused":true}}' machineconfigpool/worker
----

. To verify that the machine config pool is paused:
+
.Control plane (master) nodes
[source,terminal]
----
# oc get machineconfigpool/master --template='{{.spec.paused}}'
----
+
.Worker nodes
[source,terminal]
----
# oc get machineconfigpool/worker --template='{{.spec.paused}}'
----
+
The `spec.paused` field is `true` and the machine config pool is paused.

. Alternatively, to unpause the autoreboot process:

* As root, update the `spec.paused` field to `false` in the `MachineConfigPool` custom resource.
+
.Control plane (master) nodes
[source,terminal]
----
# oc patch --type=merge --patch='{"spec":{"paused":false}}' machineconfigpool/master
----
+
.Worker nodes
[source,terminal]
----
# oc patch --type=merge --patch='{"spec":{"paused":false}}' machineconfigpool/worker
----
+
[NOTE]
====
By unpausing a machine config pool, all paused changes are applied at reboot.
====
+
. To verify that the machine config pool is unpaused:
+
.Control plane (master) nodes
[source,terminal]
----
# oc get machineconfigpool/master --template='{{.spec.paused}}'
----
+
.Worker nodes
[source,terminal]
----
# oc get machineconfigpool/worker --template='{{.spec.paused}}'
----
+
The `spec.paused` field is `false` and the machine config pool is unpaused.

. After unpausing, to see if the machine config pool has pending changes:
+
[source,terminal]
----
# oc get machineconfigpool
----
+
.Example output
----
NAME     CONFIG                                   UPDATED   UPDATING
master   rendered-master-546383f80705bd5aeaba93   False     True
worker   rendered-worker-b4c51bb33ccaae6fc4a6a5   True      False
----
+
If *UPDATED* is *False* and *UPDATING* is *True*, there are pending changes. When *UPDATING* is *False*, there are no pending changes.

[IMPORTANT]
====
It is recommended to schedule a maintenance window for a reboot as early as possible by setting `spec.paused` to `false` so that the queued changes since last reboot will take effect.
====
