// Module included in the following assemblies:
//
// * virt/virtual_machines/vm_networking/virt-attaching-vm-to-sriov-network.adoc

:_mod-docs-content-type: PROCEDURE
[id="virt-attaching-vm-to-sriov-network_{context}"]
= Connecting a virtual machine to an SR-IOV network

You can connect the virtual machine (VM) to the SR-IOV network by including the network details in the VM configuration.

.Procedure

. Include the SR-IOV network details in the `spec.domain.devices.interfaces` and `spec.networks` of the VM configuration:
+
[source,yaml]
----
kind: VirtualMachine
...
spec:
  domain:
    devices:
      interfaces:
      - name: default
        masquerade: {}
      - name: nic1
        sriov: {}
  networks:
  - name: <default> <4>
    pod: {}
  - name: nic1
    multus:
        networkName: sriov-network
# ...
----
** `spec.template.spec.domain.devices.interfaces.name` specifies a unique name for the SR-IOV interface.
** `spec.template.spec.networks.name` specifies the name of the SR-IOV interface. This must be the same as the `interfaces.name` that you defined earlier.
** `spec.template.spec.networks.multus.networkName` specifies the name of the SR-IOV network attachment definition.

. Apply the virtual machine configuration:
+
[source,terminal]
----
$ oc apply -f <vm_sriov>.yaml
----
+
where:
+
`<vm_sriov>`:: Specifies the name of the virtual machine YAML file.
