// Module included in the following assembly:
//
// * virt/virtual_machines/advanced_vm_management/virt-automatic-bootsource-updates.adoc
//

:_mod-docs-content-type: PROCEDURE
[id="virt-verify-status-bootsource-update_{context}"]
= Verifying the status of a boot source

You can verify whether a boot source is system-defined or user-defined.

The `status` section of each boot source listed in the `status.dataImportChronTemplates` field of the `HyperConverged` CR indicates the type of boot source. For example, `commonTemplate: true` indicates a system-defined (`commonTemplate`) boot source and `status: {}` indicates a user-defined boot source.

.Procedure

. Use the `oc get` command to list the `dataImportChronTemplates` in the `HyperConverged` CR.

. Verify the status of the boot source.
+
Example output:
+
[source,yaml]
----
apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
# ...
spec:
  # ...
status:
  # ...
  dataImportCronTemplates:
  - metadata:
      annotations:
        cdi.kubevirt.io/storage.bind.immediate.requested: "true"
      name: centos-7-image-cron
    spec:
      garbageCollect: Outdated
      managedDataSource: centos7
      schedule: 55 8/12 * * *
      template:
        metadata: {}
        spec:
          source:
            registry:
              url: docker://quay.io/containerdisks/centos:7-2009
          storage:
            resources:
              requests:
                storage: 30Gi
        status: {}
    status:
      commonTemplate: true
    ...
  - metadata:
      annotations:
        cdi.kubevirt.io/storage.bind.immediate.requested: "true"
      name: user-defined-dic
    spec:
      garbageCollect: Outdated
      managedDataSource: user-defined-centos-stream8
      schedule: 55 8/12 * * *
      template:
        metadata: {}
        spec:
          source:
            registry:
              pullMethod: node
              url: docker://quay.io/containerdisks/centos-stream:8
          storage:
            resources:
              requests:
                storage: 30Gi
        status: {}
    status: {}
# ...
----
** `status.dataImportCronTemplates.status.commonTemplate` specifies a system-defined boot source.
** `status.dataImportCronTemplates.status` specifies a custom boot source.
