:context: cluster-logging-viewing
[id="cluster-logging-viewing"]
= Viewing pod logs for a resource
include::modules/common-attributes.adoc[]

toc::[]

You can view the pod log for various resources, such as builds, build configs, deployment configs, pods, and containers, by using the {product-title} CLI and the {product-title} web console. 

[NOTE]
====
Pod logs are a default feature that provides limited log viewing capability. To enhance your log viewing and retrieving experience, it is recommended that you install xref:../logging/cluster-logging.adoc[{product-title} cluster logging], which aggregates all the logs from your {product-title} cluster, such as node system audit logs, application container logs, and infrastructure logs.  You can then query, discover, and visualize your log data through the xref:../logging/cluster-logging-visualizer.adoc[Kibana interface]. 
====

// The following include statements pull in the module files that comprise
// the assembly. Include any combination of concept, procedure, or reference
// modules required to cover the user story. You can also include other
// assemblies.

include::modules/cluster-logging-viewing-logs.adoc[leveloffset=+1]
include::modules/cluster-logging-viewing-logs-console.adoc[leveloffset=+1]

