:_mod-docs-content-type: ASSEMBLY
[id="windows-node-upgrades"]
= Windows node upgrades
include::_attributes/common-attributes.adoc[]
:context: windows-node-upgrades

toc::[]

You can ensure your Windows nodes have the latest updates by upgrading the Windows Machine Config Operator (WMCO).

You can upgrade WMCO in any of the following scenarios:

* Within the current version. for example, from <10.y.z> to <10.y.z+1>.
* To a new, contiguous version. For example, from <10.y> to <10.y+1>.
* From an EUS version to another EUS version by using a Control Plane Only update. For example, from <10.y> to <10.y+2>.

include::modules/wmco-upgrades.adoc[leveloffset=+1]
include::modules/windows-upgades-eus.adoc[leveloffset=+1]

[role="_additional-resources"]
.Additional resources

* xref:../updating/updating_a_cluster/control-plane-only-update.adoc#control-plane-only-update[Performing a Control Plane Only update]


For more information on Operator upgrades using the Operator Lifecycle Manager (OLM), see xref:../operators/admin/olm-upgrading-operators.adoc#olm-upgrading-operators[Updating installed Operators].
